// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "verbatrace/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BillingLimiter is an autogenerated mock type for the BillingLimiter type
type BillingLimiter struct {
	mock.Mock
}

type BillingLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *BillingLimiter) EXPECT() *BillingLimiter_Expecter {
	return &BillingLimiter_Expecter{mock: &_m.Mock}
}

// CanExportReports provides a mock function with given fields: ctx, companyID
func (_m *BillingLimiter) CanExportReports(ctx context.Context, companyID uuid.UUID) error {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for CanExportReports")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, companyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanExportReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanExportReports'
type BillingLimiter_CanExportReports_Call struct {
	*mock.Call
}

// CanExportReports is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *BillingLimiter_Expecter) CanExportReports(ctx interface{}, companyID interface{}) *BillingLimiter_CanExportReports_Call {
	return &BillingLimiter_CanExportReports_Call{Call: _e.mock.On("CanExportReports", ctx, companyID)}
}

func (_c *BillingLimiter_CanExportReports_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *BillingLimiter_CanExportReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BillingLimiter_CanExportReports_Call) Return(_a0 error) *BillingLimiter_CanExportReports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanExportReports_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *BillingLimiter_CanExportReports_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalSubscription provides a mock function with given fields: ctx, userID
func (_m *BillingLimiter) GetPersonalSubscription(ctx context.Context, userID uuid.UUID) (models.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalSubscription")
	}

	var r0 models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BillingLimiter_GetPersonalSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalSubscription'
type BillingLimiter_GetPersonalSubscription_Call struct {
	*mock.Call
}

// GetPersonalSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *BillingLimiter_Expecter) GetPersonalSubscription(ctx interface{}, userID interface{}) *BillingLimiter_GetPersonalSubscription_Call {
	return &BillingLimiter_GetPersonalSubscription_Call{Call: _e.mock.On("GetPersonalSubscription", ctx, userID)}
}

func (_c *BillingLimiter_GetPersonalSubscription_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *BillingLimiter_GetPersonalSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BillingLimiter_GetPersonalSubscription_Call) Return(_a0 models.Subscription, _a1 error) *BillingLimiter_GetPersonalSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BillingLimiter_GetPersonalSubscription_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.Subscription, error)) *BillingLimiter_GetPersonalSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// NewBillingLimiter creates a new instance of BillingLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingLimiter {
	mock := &BillingLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
