// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Analyzer is an autogenerated mock type for the Analyzer type
type Analyzer struct {
	mock.Mock
}

type Analyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *Analyzer) EXPECT() *Analyzer_Expecter {
	return &Analyzer_Expecter{mock: &_m.Mock}
}

// Analyze provides a mock function with given fields: ctx, request
func (_m *Analyzer) Analyze(ctx context.Context, request models.AnalysisRequest) (models.AnalysisResult, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Analyze")
	}

	var r0 models.AnalysisResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AnalysisRequest) (models.AnalysisResult, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AnalysisRequest) models.AnalysisResult); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(models.AnalysisResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AnalysisRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Analyzer_Analyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyze'
type Analyzer_Analyze_Call struct {
	*mock.Call
}

// Analyze is a helper method to define mock.On call
//   - ctx context.Context
//   - request models.AnalysisRequest
func (_e *Analyzer_Expecter) Analyze(ctx interface{}, request interface{}) *Analyzer_Analyze_Call {
	return &Analyzer_Analyze_Call{Call: _e.mock.On("Analyze", ctx, request)}
}

func (_c *Analyzer_Analyze_Call) Run(run func(ctx context.Context, request models.AnalysisRequest)) *Analyzer_Analyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AnalysisRequest))
	})
	return _c
}

func (_c *Analyzer_Analyze_Call) Return(_a0 models.AnalysisResult, _a1 error) *Analyzer_Analyze_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Analyzer_Analyze_Call) RunAndReturn(run func(context.Context, models.AnalysisRequest) (models.AnalysisResult, error)) *Analyzer_Analyze_Call {
	_c.Call.Return(run)
	return _c
}

// Provider provides a mock function with no fields
func (_m *Analyzer) Provider() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Provider")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Analyzer_Provider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provider'
type Analyzer_Provider_Call struct {
	*mock.Call
}

// Provider is a helper method to define mock.On call
func (_e *Analyzer_Expecter) Provider() *Analyzer_Provider_Call {
	return &Analyzer_Provider_Call{Call: _e.mock.On("Provider")}
}

func (_c *Analyzer_Provider_Call) Run(run func()) *Analyzer_Provider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Analyzer_Provider_Call) Return(_a0 string) *Analyzer_Provider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Analyzer_Provider_Call) RunAndReturn(run func() string) *Analyzer_Provider_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalyzer creates a new instance of Analyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Analyzer {
	mock := &Analyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
