// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	models "verbatrace/monolit/internal/models"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, path
func (_m *Storage) Delete(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Storage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Storage_Expecter) Delete(ctx interface{}, path interface{}) *Storage_Delete_Call {
	return &Storage_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *Storage_Delete_Call) Run(run func(ctx context.Context, path string)) *Storage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_Delete_Call) Return(_a0 error) *Storage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *Storage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: ctx, path
func (_m *Storage) Open(ctx context.Context, path string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type Storage_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Storage_Expecter) Open(ctx interface{}, path interface{}) *Storage_Open_Call {
	return &Storage_Open_Call{Call: _e.mock.On("Open", ctx, path)}
}

func (_c *Storage_Open_Call) Run(run func(ctx context.Context, path string)) *Storage_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_Open_Call) Return(_a0 io.ReadCloser, _a1 error) *Storage_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Open_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *Storage_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenReadSeeker provides a mock function with given fields: ctx, path
func (_m *Storage) OpenReadSeeker(ctx context.Context, path string) (models.ReadSeekCloser, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for OpenReadSeeker")
	}

	var r0 models.ReadSeekCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.ReadSeekCloser, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.ReadSeekCloser); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.ReadSeekCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_OpenReadSeeker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenReadSeeker'
type Storage_OpenReadSeeker_Call struct {
	*mock.Call
}

// OpenReadSeeker is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *Storage_Expecter) OpenReadSeeker(ctx interface{}, path interface{}) *Storage_OpenReadSeeker_Call {
	return &Storage_OpenReadSeeker_Call{Call: _e.mock.On("OpenReadSeeker", ctx, path)}
}

func (_c *Storage_OpenReadSeeker_Call) Run(run func(ctx context.Context, path string)) *Storage_OpenReadSeeker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_OpenReadSeeker_Call) Return(_a0 models.ReadSeekCloser, _a1 error) *Storage_OpenReadSeeker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_OpenReadSeeker_Call) RunAndReturn(run func(context.Context, string) (models.ReadSeekCloser, error)) *Storage_OpenReadSeeker_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, input
func (_m *Storage) Save(ctx context.Context, input models.SaveInput) (models.SavedFile, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 models.SavedFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SaveInput) (models.SavedFile, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.SaveInput) models.SavedFile); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.SavedFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.SaveInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Storage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.SaveInput
func (_e *Storage_Expecter) Save(ctx interface{}, input interface{}) *Storage_Save_Call {
	return &Storage_Save_Call{Call: _e.mock.On("Save", ctx, input)}
}

func (_c *Storage_Save_Call) Run(run func(ctx context.Context, input models.SaveInput)) *Storage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.SaveInput))
	})
	return _c
}

func (_c *Storage_Save_Call) Return(_a0 models.SavedFile, _a1 error) *Storage_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_Save_Call) RunAndReturn(run func(context.Context, models.SaveInput) (models.SavedFile, error)) *Storage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
