// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ASRCacheStorage is an autogenerated mock type for the ASRCacheStorage type
type ASRCacheStorage struct {
	mock.Mock
}

type ASRCacheStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *ASRCacheStorage) EXPECT() *ASRCacheStorage_Expecter {
	return &ASRCacheStorage_Expecter{mock: &_m.Mock}
}

// EnsureASRCache provides a mock function with given fields: ctx, sourcePath, cachePath
func (_m *ASRCacheStorage) EnsureASRCache(ctx context.Context, sourcePath string, cachePath string) (bool, error) {
	ret := _m.Called(ctx, sourcePath, cachePath)

	if len(ret) == 0 {
		panic("no return value specified for EnsureASRCache")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, sourcePath, cachePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, sourcePath, cachePath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sourcePath, cachePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ASRCacheStorage_EnsureASRCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureASRCache'
type ASRCacheStorage_EnsureASRCache_Call struct {
	*mock.Call
}

// EnsureASRCache is a helper method to define mock.On call
//   - ctx context.Context
//   - sourcePath string
//   - cachePath string
func (_e *ASRCacheStorage_Expecter) EnsureASRCache(ctx interface{}, sourcePath interface{}, cachePath interface{}) *ASRCacheStorage_EnsureASRCache_Call {
	return &ASRCacheStorage_EnsureASRCache_Call{Call: _e.mock.On("EnsureASRCache", ctx, sourcePath, cachePath)}
}

func (_c *ASRCacheStorage_EnsureASRCache_Call) Run(run func(ctx context.Context, sourcePath string, cachePath string)) *ASRCacheStorage_EnsureASRCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ASRCacheStorage_EnsureASRCache_Call) Return(reused bool, err error) *ASRCacheStorage_EnsureASRCache_Call {
	_c.Call.Return(reused, err)
	return _c
}

func (_c *ASRCacheStorage_EnsureASRCache_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ASRCacheStorage_EnsureASRCache_Call {
	_c.Call.Return(run)
	return _c
}

// NewASRCacheStorage creates a new instance of ASRCacheStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewASRCacheStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *ASRCacheStorage {
	mock := &ASRCacheStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
