// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// CallRepository is an autogenerated mock type for the CallRepository type
type CallRepository struct {
	mock.Mock
}

type CallRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CallRepository) EXPECT() *CallRepository_Expecter {
	return &CallRepository_Expecter{mock: &_m.Mock}
}

// CanManageCall provides a mock function with given fields: ctx, id, userID
func (_m *CallRepository) CanManageCall(ctx context.Context, id uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanManageCall")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_CanManageCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanManageCall'
type CallRepository_CanManageCall_Call struct {
	*mock.Call
}

// CanManageCall is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *CallRepository_Expecter) CanManageCall(ctx interface{}, id interface{}, userID interface{}) *CallRepository_CanManageCall_Call {
	return &CallRepository_CanManageCall_Call{Call: _e.mock.On("CanManageCall", ctx, id, userID)}
}

func (_c *CallRepository_CanManageCall_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *CallRepository_CanManageCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *CallRepository_CanManageCall_Call) Return(_a0 bool, _a1 error) *CallRepository_CanManageCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_CanManageCall_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *CallRepository_CanManageCall_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCall provides a mock function with given fields: ctx, call
func (_m *CallRepository) CreateCall(ctx context.Context, call models.Call) (models.Call, error) {
	ret := _m.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for CreateCall")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Call) (models.Call, error)); ok {
		return rf(ctx, call)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Call) models.Call); ok {
		r0 = rf(ctx, call)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Call) error); ok {
		r1 = rf(ctx, call)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_CreateCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCall'
type CallRepository_CreateCall_Call struct {
	*mock.Call
}

// CreateCall is a helper method to define mock.On call
//   - ctx context.Context
//   - call models.Call
func (_e *CallRepository_Expecter) CreateCall(ctx interface{}, call interface{}) *CallRepository_CreateCall_Call {
	return &CallRepository_CreateCall_Call{Call: _e.mock.On("CreateCall", ctx, call)}
}

func (_c *CallRepository_CreateCall_Call) Run(run func(ctx context.Context, call models.Call)) *CallRepository_CreateCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Call))
	})
	return _c
}

func (_c *CallRepository_CreateCall_Call) Return(_a0 models.Call, _a1 error) *CallRepository_CreateCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_CreateCall_Call) RunAndReturn(run func(context.Context, models.Call) (models.Call, error)) *CallRepository_CreateCall_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCallWithProcessingJob provides a mock function with given fields: ctx, call, job
func (_m *CallRepository) CreateCallWithProcessingJob(ctx context.Context, call models.Call, job models.ProcessingJob) (models.Call, error) {
	ret := _m.Called(ctx, call, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateCallWithProcessingJob")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Call, models.ProcessingJob) (models.Call, error)); ok {
		return rf(ctx, call, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Call, models.ProcessingJob) models.Call); ok {
		r0 = rf(ctx, call, job)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Call, models.ProcessingJob) error); ok {
		r1 = rf(ctx, call, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_CreateCallWithProcessingJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCallWithProcessingJob'
type CallRepository_CreateCallWithProcessingJob_Call struct {
	*mock.Call
}

// CreateCallWithProcessingJob is a helper method to define mock.On call
//   - ctx context.Context
//   - call models.Call
//   - job models.ProcessingJob
func (_e *CallRepository_Expecter) CreateCallWithProcessingJob(ctx interface{}, call interface{}, job interface{}) *CallRepository_CreateCallWithProcessingJob_Call {
	return &CallRepository_CreateCallWithProcessingJob_Call{Call: _e.mock.On("CreateCallWithProcessingJob", ctx, call, job)}
}

func (_c *CallRepository_CreateCallWithProcessingJob_Call) Run(run func(ctx context.Context, call models.Call, job models.ProcessingJob)) *CallRepository_CreateCallWithProcessingJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Call), args[2].(models.ProcessingJob))
	})
	return _c
}

func (_c *CallRepository_CreateCallWithProcessingJob_Call) Return(_a0 models.Call, _a1 error) *CallRepository_CreateCallWithProcessingJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_CreateCallWithProcessingJob_Call) RunAndReturn(run func(context.Context, models.Call, models.ProcessingJob) (models.Call, error)) *CallRepository_CreateCallWithProcessingJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function with given fields: ctx, id, userID
func (_m *CallRepository) GetByUUID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (models.Call, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Call, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Call); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type CallRepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *CallRepository_Expecter) GetByUUID(ctx interface{}, id interface{}, userID interface{}) *CallRepository_GetByUUID_Call {
	return &CallRepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, id, userID)}
}

func (_c *CallRepository_GetByUUID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *CallRepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *CallRepository_GetByUUID_Call) Return(_a0 models.Call, _a1 error) *CallRepository_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_GetByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.Call, error)) *CallRepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUIDForProcessing provides a mock function with given fields: ctx, id
func (_m *CallRepository) GetByUUIDForProcessing(ctx context.Context, id uuid.UUID) (models.Call, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUIDForProcessing")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Call, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Call); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_GetByUUIDForProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUIDForProcessing'
type CallRepository_GetByUUIDForProcessing_Call struct {
	*mock.Call
}

// GetByUUIDForProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CallRepository_Expecter) GetByUUIDForProcessing(ctx interface{}, id interface{}) *CallRepository_GetByUUIDForProcessing_Call {
	return &CallRepository_GetByUUIDForProcessing_Call{Call: _e.mock.On("GetByUUIDForProcessing", ctx, id)}
}

func (_c *CallRepository_GetByUUIDForProcessing_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CallRepository_GetByUUIDForProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CallRepository_GetByUUIDForProcessing_Call) Return(_a0 models.Call, _a1 error) *CallRepository_GetByUUIDForProcessing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_GetByUUIDForProcessing_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.Call, error)) *CallRepository_GetByUUIDForProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilterOptions provides a mock function with given fields: ctx, input
func (_m *CallRepository) GetFilterOptions(ctx context.Context, input models.CallFilterOptionsInput) (models.CallFilterOptions, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetFilterOptions")
	}

	var r0 models.CallFilterOptions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CallFilterOptionsInput) (models.CallFilterOptions, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CallFilterOptionsInput) models.CallFilterOptions); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CallFilterOptions)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CallFilterOptionsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_GetFilterOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilterOptions'
type CallRepository_GetFilterOptions_Call struct {
	*mock.Call
}

// GetFilterOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CallFilterOptionsInput
func (_e *CallRepository_Expecter) GetFilterOptions(ctx interface{}, input interface{}) *CallRepository_GetFilterOptions_Call {
	return &CallRepository_GetFilterOptions_Call{Call: _e.mock.On("GetFilterOptions", ctx, input)}
}

func (_c *CallRepository_GetFilterOptions_Call) Run(run func(ctx context.Context, input models.CallFilterOptionsInput)) *CallRepository_GetFilterOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CallFilterOptionsInput))
	})
	return _c
}

func (_c *CallRepository_GetFilterOptions_Call) Return(_a0 models.CallFilterOptions, _a1 error) *CallRepository_GetFilterOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_GetFilterOptions_Call) RunAndReturn(run func(context.Context, models.CallFilterOptionsInput) (models.CallFilterOptions, error)) *CallRepository_GetFilterOptions_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *CallRepository) List(ctx context.Context, userID uuid.UUID) ([]models.Call, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Call, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Call); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Call)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CallRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *CallRepository_Expecter) List(ctx interface{}, userID interface{}) *CallRepository_List_Call {
	return &CallRepository_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *CallRepository_List_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *CallRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CallRepository_List_Call) Return(_a0 []models.Call, _a1 error) *CallRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Call, error)) *CallRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeletedCalls provides a mock function with given fields: ctx, input
func (_m *CallRepository) ListDeletedCalls(ctx context.Context, input models.ListDeletedCallsInput) (models.ListDeletedCallsResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListDeletedCalls")
	}

	var r0 models.ListDeletedCallsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListDeletedCallsInput) (models.ListDeletedCallsResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListDeletedCallsInput) models.ListDeletedCallsResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ListDeletedCallsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListDeletedCallsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_ListDeletedCalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeletedCalls'
type CallRepository_ListDeletedCalls_Call struct {
	*mock.Call
}

// ListDeletedCalls is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListDeletedCallsInput
func (_e *CallRepository_Expecter) ListDeletedCalls(ctx interface{}, input interface{}) *CallRepository_ListDeletedCalls_Call {
	return &CallRepository_ListDeletedCalls_Call{Call: _e.mock.On("ListDeletedCalls", ctx, input)}
}

func (_c *CallRepository_ListDeletedCalls_Call) Run(run func(ctx context.Context, input models.ListDeletedCallsInput)) *CallRepository_ListDeletedCalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListDeletedCallsInput))
	})
	return _c
}

func (_c *CallRepository_ListDeletedCalls_Call) Return(_a0 models.ListDeletedCallsResult, _a1 error) *CallRepository_ListDeletedCalls_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_ListDeletedCalls_Call) RunAndReturn(run func(context.Context, models.ListDeletedCallsInput) (models.ListDeletedCallsResult, error)) *CallRepository_ListDeletedCalls_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiltered provides a mock function with given fields: ctx, input
func (_m *CallRepository) ListFiltered(ctx context.Context, input models.ListCallsInput) (models.ListCallsResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListFiltered")
	}

	var r0 models.ListCallsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListCallsInput) (models.ListCallsResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListCallsInput) models.ListCallsResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ListCallsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListCallsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_ListFiltered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiltered'
type CallRepository_ListFiltered_Call struct {
	*mock.Call
}

// ListFiltered is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListCallsInput
func (_e *CallRepository_Expecter) ListFiltered(ctx interface{}, input interface{}) *CallRepository_ListFiltered_Call {
	return &CallRepository_ListFiltered_Call{Call: _e.mock.On("ListFiltered", ctx, input)}
}

func (_c *CallRepository_ListFiltered_Call) Run(run func(ctx context.Context, input models.ListCallsInput)) *CallRepository_ListFiltered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListCallsInput))
	})
	return _c
}

func (_c *CallRepository_ListFiltered_Call) Return(_a0 models.ListCallsResult, _a1 error) *CallRepository_ListFiltered_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_ListFiltered_Call) RunAndReturn(run func(context.Context, models.ListCallsInput) (models.ListCallsResult, error)) *CallRepository_ListFiltered_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCall provides a mock function with given fields: ctx, id, userID
func (_m *CallRepository) RestoreCall(ctx context.Context, id uuid.UUID, userID uuid.UUID) (models.Call, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCall")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Call, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Call); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_RestoreCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCall'
type CallRepository_RestoreCall_Call struct {
	*mock.Call
}

// RestoreCall is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *CallRepository_Expecter) RestoreCall(ctx interface{}, id interface{}, userID interface{}) *CallRepository_RestoreCall_Call {
	return &CallRepository_RestoreCall_Call{Call: _e.mock.On("RestoreCall", ctx, id, userID)}
}

func (_c *CallRepository_RestoreCall_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *CallRepository_RestoreCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *CallRepository_RestoreCall_Call) Return(_a0 models.Call, _a1 error) *CallRepository_RestoreCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_RestoreCall_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.Call, error)) *CallRepository_RestoreCall_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteCall provides a mock function with given fields: ctx, id, userID, now, purgeAfter
func (_m *CallRepository) SoftDeleteCall(ctx context.Context, id uuid.UUID, userID uuid.UUID, now time.Time, purgeAfter time.Time) (models.Call, error) {
	ret := _m.Called(ctx, id, userID, now, purgeAfter)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteCall")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) (models.Call, error)); ok {
		return rf(ctx, id, userID, now, purgeAfter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) models.Call); ok {
		r0 = rf(ctx, id, userID, now, purgeAfter)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, id, userID, now, purgeAfter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_SoftDeleteCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteCall'
type CallRepository_SoftDeleteCall_Call struct {
	*mock.Call
}

// SoftDeleteCall is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - now time.Time
//   - purgeAfter time.Time
func (_e *CallRepository_Expecter) SoftDeleteCall(ctx interface{}, id interface{}, userID interface{}, now interface{}, purgeAfter interface{}) *CallRepository_SoftDeleteCall_Call {
	return &CallRepository_SoftDeleteCall_Call{Call: _e.mock.On("SoftDeleteCall", ctx, id, userID, now, purgeAfter)}
}

func (_c *CallRepository_SoftDeleteCall_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, now time.Time, purgeAfter time.Time)) *CallRepository_SoftDeleteCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *CallRepository_SoftDeleteCall_Call) Return(_a0 models.Call, _a1 error) *CallRepository_SoftDeleteCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_SoftDeleteCall_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) (models.Call, error)) *CallRepository_SoftDeleteCall_Call {
	_c.Call.Return(run)
	return _c
}

// TakeNextForProcessing provides a mock function with given fields: ctx
func (_m *CallRepository) TakeNextForProcessing(ctx context.Context) (models.Call, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TakeNextForProcessing")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (models.Call, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) models.Call); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_TakeNextForProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TakeNextForProcessing'
type CallRepository_TakeNextForProcessing_Call struct {
	*mock.Call
}

// TakeNextForProcessing is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CallRepository_Expecter) TakeNextForProcessing(ctx interface{}) *CallRepository_TakeNextForProcessing_Call {
	return &CallRepository_TakeNextForProcessing_Call{Call: _e.mock.On("TakeNextForProcessing", ctx)}
}

func (_c *CallRepository_TakeNextForProcessing_Call) Run(run func(ctx context.Context)) *CallRepository_TakeNextForProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CallRepository_TakeNextForProcessing_Call) Return(_a0 models.Call, _a1 error) *CallRepository_TakeNextForProcessing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_TakeNextForProcessing_Call) RunAndReturn(run func(context.Context) (models.Call, error)) *CallRepository_TakeNextForProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCallStatus provides a mock function with given fields: ctx, id, status
func (_m *CallRepository) UpdateCallStatus(ctx context.Context, id uuid.UUID, status models.CallStatus) (models.Call, error) {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCallStatus")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.CallStatus) (models.Call, error)); ok {
		return rf(ctx, id, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.CallStatus) models.Call); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.CallStatus) error); ok {
		r1 = rf(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_UpdateCallStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCallStatus'
type CallRepository_UpdateCallStatus_Call struct {
	*mock.Call
}

// UpdateCallStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status models.CallStatus
func (_e *CallRepository_Expecter) UpdateCallStatus(ctx interface{}, id interface{}, status interface{}) *CallRepository_UpdateCallStatus_Call {
	return &CallRepository_UpdateCallStatus_Call{Call: _e.mock.On("UpdateCallStatus", ctx, id, status)}
}

func (_c *CallRepository_UpdateCallStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status models.CallStatus)) *CallRepository_UpdateCallStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.CallStatus))
	})
	return _c
}

func (_c *CallRepository_UpdateCallStatus_Call) Return(_a0 models.Call, _a1 error) *CallRepository_UpdateCallStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_UpdateCallStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.CallStatus) (models.Call, error)) *CallRepository_UpdateCallStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCallTitle provides a mock function with given fields: ctx, id, userID, title
func (_m *CallRepository) UpdateCallTitle(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string) (models.Call, error) {
	ret := _m.Called(ctx, id, userID, title)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCallTitle")
	}

	var r0 models.Call
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (models.Call, error)); ok {
		return rf(ctx, id, userID, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) models.Call); ok {
		r0 = rf(ctx, id, userID, title)
	} else {
		r0 = ret.Get(0).(models.Call)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, userID, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallRepository_UpdateCallTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCallTitle'
type CallRepository_UpdateCallTitle_Call struct {
	*mock.Call
}

// UpdateCallTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - title string
func (_e *CallRepository_Expecter) UpdateCallTitle(ctx interface{}, id interface{}, userID interface{}, title interface{}) *CallRepository_UpdateCallTitle_Call {
	return &CallRepository_UpdateCallTitle_Call{Call: _e.mock.On("UpdateCallTitle", ctx, id, userID, title)}
}

func (_c *CallRepository_UpdateCallTitle_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string)) *CallRepository_UpdateCallTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *CallRepository_UpdateCallTitle_Call) Return(_a0 models.Call, _a1 error) *CallRepository_UpdateCallTitle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CallRepository_UpdateCallTitle_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (models.Call, error)) *CallRepository_UpdateCallTitle_Call {
	_c.Call.Return(run)
	return _c
}

// NewCallRepository creates a new instance of CallRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCallRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CallRepository {
	mock := &CallRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
