// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ContactRepository is an autogenerated mock type for the ContactRepository type
type ContactRepository struct {
	mock.Mock
}

type ContactRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ContactRepository) EXPECT() *ContactRepository_Expecter {
	return &ContactRepository_Expecter{mock: &_m.Mock}
}

// AddContact provides a mock function with given fields: ctx, userID, contactID
func (_m *ContactRepository) AddContact(ctx context.Context, userID uuid.UUID, contactID uuid.UUID) error {
	ret := _m.Called(ctx, userID, contactID)

	if len(ret) == 0 {
		panic("no return value specified for AddContact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, contactID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContactRepository_AddContact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddContact'
type ContactRepository_AddContact_Call struct {
	*mock.Call
}

// AddContact is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - contactID uuid.UUID
func (_e *ContactRepository_Expecter) AddContact(ctx interface{}, userID interface{}, contactID interface{}) *ContactRepository_AddContact_Call {
	return &ContactRepository_AddContact_Call{Call: _e.mock.On("AddContact", ctx, userID, contactID)}
}

func (_c *ContactRepository_AddContact_Call) Run(run func(ctx context.Context, userID uuid.UUID, contactID uuid.UUID)) *ContactRepository_AddContact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ContactRepository_AddContact_Call) Return(_a0 error) *ContactRepository_AddContact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContactRepository_AddContact_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ContactRepository_AddContact_Call {
	_c.Call.Return(run)
	return _c
}

// AddFavoriteCall provides a mock function with given fields: ctx, userID, callID
func (_m *ContactRepository) AddFavoriteCall(ctx context.Context, userID uuid.UUID, callID uuid.UUID) error {
	ret := _m.Called(ctx, userID, callID)

	if len(ret) == 0 {
		panic("no return value specified for AddFavoriteCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, callID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContactRepository_AddFavoriteCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFavoriteCall'
type ContactRepository_AddFavoriteCall_Call struct {
	*mock.Call
}

// AddFavoriteCall is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - callID uuid.UUID
func (_e *ContactRepository_Expecter) AddFavoriteCall(ctx interface{}, userID interface{}, callID interface{}) *ContactRepository_AddFavoriteCall_Call {
	return &ContactRepository_AddFavoriteCall_Call{Call: _e.mock.On("AddFavoriteCall", ctx, userID, callID)}
}

func (_c *ContactRepository_AddFavoriteCall_Call) Run(run func(ctx context.Context, userID uuid.UUID, callID uuid.UUID)) *ContactRepository_AddFavoriteCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ContactRepository_AddFavoriteCall_Call) Return(_a0 error) *ContactRepository_AddFavoriteCall_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContactRepository_AddFavoriteCall_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ContactRepository_AddFavoriteCall_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicUserByUUID provides a mock function with given fields: ctx, userID
func (_m *ContactRepository) GetPublicUserByUUID(ctx context.Context, userID uuid.UUID) (models.PublicUser, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicUserByUUID")
	}

	var r0 models.PublicUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.PublicUser, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.PublicUser); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.PublicUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContactRepository_GetPublicUserByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicUserByUUID'
type ContactRepository_GetPublicUserByUUID_Call struct {
	*mock.Call
}

// GetPublicUserByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ContactRepository_Expecter) GetPublicUserByUUID(ctx interface{}, userID interface{}) *ContactRepository_GetPublicUserByUUID_Call {
	return &ContactRepository_GetPublicUserByUUID_Call{Call: _e.mock.On("GetPublicUserByUUID", ctx, userID)}
}

func (_c *ContactRepository_GetPublicUserByUUID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ContactRepository_GetPublicUserByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ContactRepository_GetPublicUserByUUID_Call) Return(_a0 models.PublicUser, _a1 error) *ContactRepository_GetPublicUserByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContactRepository_GetPublicUserByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.PublicUser, error)) *ContactRepository_GetPublicUserByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListContactIDs provides a mock function with given fields: ctx, userID
func (_m *ContactRepository) ListContactIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListContactIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContactRepository_ListContactIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContactIDs'
type ContactRepository_ListContactIDs_Call struct {
	*mock.Call
}

// ListContactIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ContactRepository_Expecter) ListContactIDs(ctx interface{}, userID interface{}) *ContactRepository_ListContactIDs_Call {
	return &ContactRepository_ListContactIDs_Call{Call: _e.mock.On("ListContactIDs", ctx, userID)}
}

func (_c *ContactRepository_ListContactIDs_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ContactRepository_ListContactIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ContactRepository_ListContactIDs_Call) Return(_a0 []uuid.UUID, _a1 error) *ContactRepository_ListContactIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContactRepository_ListContactIDs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *ContactRepository_ListContactIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListFavoriteCallIDs provides a mock function with given fields: ctx, userID
func (_m *ContactRepository) ListFavoriteCallIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListFavoriteCallIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContactRepository_ListFavoriteCallIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFavoriteCallIDs'
type ContactRepository_ListFavoriteCallIDs_Call struct {
	*mock.Call
}

// ListFavoriteCallIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *ContactRepository_Expecter) ListFavoriteCallIDs(ctx interface{}, userID interface{}) *ContactRepository_ListFavoriteCallIDs_Call {
	return &ContactRepository_ListFavoriteCallIDs_Call{Call: _e.mock.On("ListFavoriteCallIDs", ctx, userID)}
}

func (_c *ContactRepository_ListFavoriteCallIDs_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *ContactRepository_ListFavoriteCallIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ContactRepository_ListFavoriteCallIDs_Call) Return(_a0 []uuid.UUID, _a1 error) *ContactRepository_ListFavoriteCallIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContactRepository_ListFavoriteCallIDs_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *ContactRepository_ListFavoriteCallIDs_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContact provides a mock function with given fields: ctx, userID, contactID
func (_m *ContactRepository) RemoveContact(ctx context.Context, userID uuid.UUID, contactID uuid.UUID) error {
	ret := _m.Called(ctx, userID, contactID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, contactID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContactRepository_RemoveContact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContact'
type ContactRepository_RemoveContact_Call struct {
	*mock.Call
}

// RemoveContact is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - contactID uuid.UUID
func (_e *ContactRepository_Expecter) RemoveContact(ctx interface{}, userID interface{}, contactID interface{}) *ContactRepository_RemoveContact_Call {
	return &ContactRepository_RemoveContact_Call{Call: _e.mock.On("RemoveContact", ctx, userID, contactID)}
}

func (_c *ContactRepository_RemoveContact_Call) Run(run func(ctx context.Context, userID uuid.UUID, contactID uuid.UUID)) *ContactRepository_RemoveContact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ContactRepository_RemoveContact_Call) Return(_a0 error) *ContactRepository_RemoveContact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContactRepository_RemoveContact_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ContactRepository_RemoveContact_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFavoriteCall provides a mock function with given fields: ctx, userID, callID
func (_m *ContactRepository) RemoveFavoriteCall(ctx context.Context, userID uuid.UUID, callID uuid.UUID) error {
	ret := _m.Called(ctx, userID, callID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFavoriteCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, callID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContactRepository_RemoveFavoriteCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFavoriteCall'
type ContactRepository_RemoveFavoriteCall_Call struct {
	*mock.Call
}

// RemoveFavoriteCall is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - callID uuid.UUID
func (_e *ContactRepository_Expecter) RemoveFavoriteCall(ctx interface{}, userID interface{}, callID interface{}) *ContactRepository_RemoveFavoriteCall_Call {
	return &ContactRepository_RemoveFavoriteCall_Call{Call: _e.mock.On("RemoveFavoriteCall", ctx, userID, callID)}
}

func (_c *ContactRepository_RemoveFavoriteCall_Call) Run(run func(ctx context.Context, userID uuid.UUID, callID uuid.UUID)) *ContactRepository_RemoveFavoriteCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ContactRepository_RemoveFavoriteCall_Call) Return(_a0 error) *ContactRepository_RemoveFavoriteCall_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContactRepository_RemoveFavoriteCall_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ContactRepository_RemoveFavoriteCall_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPublicUsers provides a mock function with given fields: ctx, usernamePrefix, limit
func (_m *ContactRepository) SearchPublicUsers(ctx context.Context, usernamePrefix string, limit int) ([]models.PublicUser, error) {
	ret := _m.Called(ctx, usernamePrefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchPublicUsers")
	}

	var r0 []models.PublicUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]models.PublicUser, error)); ok {
		return rf(ctx, usernamePrefix, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []models.PublicUser); ok {
		r0 = rf(ctx, usernamePrefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PublicUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, usernamePrefix, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContactRepository_SearchPublicUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPublicUsers'
type ContactRepository_SearchPublicUsers_Call struct {
	*mock.Call
}

// SearchPublicUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - usernamePrefix string
//   - limit int
func (_e *ContactRepository_Expecter) SearchPublicUsers(ctx interface{}, usernamePrefix interface{}, limit interface{}) *ContactRepository_SearchPublicUsers_Call {
	return &ContactRepository_SearchPublicUsers_Call{Call: _e.mock.On("SearchPublicUsers", ctx, usernamePrefix, limit)}
}

func (_c *ContactRepository_SearchPublicUsers_Call) Run(run func(ctx context.Context, usernamePrefix string, limit int)) *ContactRepository_SearchPublicUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *ContactRepository_SearchPublicUsers_Call) Return(_a0 []models.PublicUser, _a1 error) *ContactRepository_SearchPublicUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContactRepository_SearchPublicUsers_Call) RunAndReturn(run func(context.Context, string, int) ([]models.PublicUser, error)) *ContactRepository_SearchPublicUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewContactRepository creates a new instance of ContactRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContactRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContactRepository {
	mock := &ContactRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
