// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "verbatrace/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserPreferencesRepository is an autogenerated mock type for the UserPreferencesRepository type
type UserPreferencesRepository struct {
	mock.Mock
}

type UserPreferencesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserPreferencesRepository) EXPECT() *UserPreferencesRepository_Expecter {
	return &UserPreferencesRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID
func (_m *UserPreferencesRepository) Get(ctx context.Context, userID uuid.UUID) (models.UserPreferences, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.UserPreferences, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.UserPreferences); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.UserPreferences)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPreferencesRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserPreferencesRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserPreferencesRepository_Expecter) Get(ctx interface{}, userID interface{}) *UserPreferencesRepository_Get_Call {
	return &UserPreferencesRepository_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *UserPreferencesRepository_Get_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserPreferencesRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserPreferencesRepository_Get_Call) Return(_a0 models.UserPreferences, _a1 error) *UserPreferencesRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserPreferencesRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.UserPreferences, error)) *UserPreferencesRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, input
func (_m *UserPreferencesRepository) Upsert(ctx context.Context, input models.UpdateUserPreferencesInput) (models.UserPreferences, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 models.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUserPreferencesInput) (models.UserPreferences, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUserPreferencesInput) models.UserPreferences); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.UserPreferences)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateUserPreferencesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPreferencesRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type UserPreferencesRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateUserPreferencesInput
func (_e *UserPreferencesRepository_Expecter) Upsert(ctx interface{}, input interface{}) *UserPreferencesRepository_Upsert_Call {
	return &UserPreferencesRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, input)}
}

func (_c *UserPreferencesRepository_Upsert_Call) Run(run func(ctx context.Context, input models.UpdateUserPreferencesInput)) *UserPreferencesRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateUserPreferencesInput))
	})
	return _c
}

func (_c *UserPreferencesRepository_Upsert_Call) Return(_a0 models.UserPreferences, _a1 error) *UserPreferencesRepository_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserPreferencesRepository_Upsert_Call) RunAndReturn(run func(context.Context, models.UpdateUserPreferencesInput) (models.UserPreferences, error)) *UserPreferencesRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserPreferencesRepository creates a new instance of UserPreferencesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPreferencesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPreferencesRepository {
	mock := &UserPreferencesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
