// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// InvitationService is an autogenerated mock type for the InvitationService type
type InvitationService struct {
	mock.Mock
}

type InvitationService_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationService) EXPECT() *InvitationService_Expecter {
	return &InvitationService_Expecter{mock: &_m.Mock}
}

// AcceptInvitation provides a mock function with given fields: ctx, input
func (_m *InvitationService) AcceptInvitation(ctx context.Context, input models.AcceptInvitationInput) (models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvitation")
	}

	var r0 models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AcceptInvitationInput) (models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AcceptInvitationInput) models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.MembershipInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AcceptInvitationInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_AcceptInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvitation'
type InvitationService_AcceptInvitation_Call struct {
	*mock.Call
}

// AcceptInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AcceptInvitationInput
func (_e *InvitationService_Expecter) AcceptInvitation(ctx interface{}, input interface{}) *InvitationService_AcceptInvitation_Call {
	return &InvitationService_AcceptInvitation_Call{Call: _e.mock.On("AcceptInvitation", ctx, input)}
}

func (_c *InvitationService_AcceptInvitation_Call) Run(run func(ctx context.Context, input models.AcceptInvitationInput)) *InvitationService_AcceptInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AcceptInvitationInput))
	})
	return _c
}

func (_c *InvitationService_AcceptInvitation_Call) Return(_a0 models.MembershipInvitation, _a1 error) *InvitationService_AcceptInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_AcceptInvitation_Call) RunAndReturn(run func(context.Context, models.AcceptInvitationInput) (models.MembershipInvitation, error)) *InvitationService_AcceptInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CancelInvitation provides a mock function with given fields: ctx, input
func (_m *InvitationService) CancelInvitation(ctx context.Context, input models.CancelInvitationInput) (models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvitation")
	}

	var r0 models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CancelInvitationInput) (models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CancelInvitationInput) models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.MembershipInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CancelInvitationInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_CancelInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelInvitation'
type InvitationService_CancelInvitation_Call struct {
	*mock.Call
}

// CancelInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CancelInvitationInput
func (_e *InvitationService_Expecter) CancelInvitation(ctx interface{}, input interface{}) *InvitationService_CancelInvitation_Call {
	return &InvitationService_CancelInvitation_Call{Call: _e.mock.On("CancelInvitation", ctx, input)}
}

func (_c *InvitationService_CancelInvitation_Call) Run(run func(ctx context.Context, input models.CancelInvitationInput)) *InvitationService_CancelInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CancelInvitationInput))
	})
	return _c
}

func (_c *InvitationService_CancelInvitation_Call) Return(_a0 models.MembershipInvitation, _a1 error) *InvitationService_CancelInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_CancelInvitation_Call) RunAndReturn(run func(context.Context, models.CancelInvitationInput) (models.MembershipInvitation, error)) *InvitationService_CancelInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCompanyInvitation provides a mock function with given fields: ctx, input
func (_m *InvitationService) CreateCompanyInvitation(ctx context.Context, input models.CreateCompanyInvitationInput) (models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompanyInvitation")
	}

	var r0 models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateCompanyInvitationInput) (models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateCompanyInvitationInput) models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.MembershipInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateCompanyInvitationInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_CreateCompanyInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompanyInvitation'
type InvitationService_CreateCompanyInvitation_Call struct {
	*mock.Call
}

// CreateCompanyInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateCompanyInvitationInput
func (_e *InvitationService_Expecter) CreateCompanyInvitation(ctx interface{}, input interface{}) *InvitationService_CreateCompanyInvitation_Call {
	return &InvitationService_CreateCompanyInvitation_Call{Call: _e.mock.On("CreateCompanyInvitation", ctx, input)}
}

func (_c *InvitationService_CreateCompanyInvitation_Call) Run(run func(ctx context.Context, input models.CreateCompanyInvitationInput)) *InvitationService_CreateCompanyInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateCompanyInvitationInput))
	})
	return _c
}

func (_c *InvitationService_CreateCompanyInvitation_Call) Return(_a0 models.MembershipInvitation, _a1 error) *InvitationService_CreateCompanyInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_CreateCompanyInvitation_Call) RunAndReturn(run func(context.Context, models.CreateCompanyInvitationInput) (models.MembershipInvitation, error)) *InvitationService_CreateCompanyInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDepartmentInvitation provides a mock function with given fields: ctx, input
func (_m *InvitationService) CreateDepartmentInvitation(ctx context.Context, input models.CreateDepartmentInvitationInput) (models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateDepartmentInvitation")
	}

	var r0 models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDepartmentInvitationInput) (models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDepartmentInvitationInput) models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.MembershipInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateDepartmentInvitationInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_CreateDepartmentInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDepartmentInvitation'
type InvitationService_CreateDepartmentInvitation_Call struct {
	*mock.Call
}

// CreateDepartmentInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateDepartmentInvitationInput
func (_e *InvitationService_Expecter) CreateDepartmentInvitation(ctx interface{}, input interface{}) *InvitationService_CreateDepartmentInvitation_Call {
	return &InvitationService_CreateDepartmentInvitation_Call{Call: _e.mock.On("CreateDepartmentInvitation", ctx, input)}
}

func (_c *InvitationService_CreateDepartmentInvitation_Call) Run(run func(ctx context.Context, input models.CreateDepartmentInvitationInput)) *InvitationService_CreateDepartmentInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateDepartmentInvitationInput))
	})
	return _c
}

func (_c *InvitationService_CreateDepartmentInvitation_Call) Return(_a0 models.MembershipInvitation, _a1 error) *InvitationService_CreateDepartmentInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_CreateDepartmentInvitation_Call) RunAndReturn(run func(context.Context, models.CreateDepartmentInvitationInput) (models.MembershipInvitation, error)) *InvitationService_CreateDepartmentInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// DecideInvitationApproval provides a mock function with given fields: ctx, input
func (_m *InvitationService) DecideInvitationApproval(ctx context.Context, input models.DecideInvitationApprovalInput) (models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DecideInvitationApproval")
	}

	var r0 models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.DecideInvitationApprovalInput) (models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.DecideInvitationApprovalInput) models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.MembershipInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.DecideInvitationApprovalInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_DecideInvitationApproval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideInvitationApproval'
type InvitationService_DecideInvitationApproval_Call struct {
	*mock.Call
}

// DecideInvitationApproval is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.DecideInvitationApprovalInput
func (_e *InvitationService_Expecter) DecideInvitationApproval(ctx interface{}, input interface{}) *InvitationService_DecideInvitationApproval_Call {
	return &InvitationService_DecideInvitationApproval_Call{Call: _e.mock.On("DecideInvitationApproval", ctx, input)}
}

func (_c *InvitationService_DecideInvitationApproval_Call) Run(run func(ctx context.Context, input models.DecideInvitationApprovalInput)) *InvitationService_DecideInvitationApproval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.DecideInvitationApprovalInput))
	})
	return _c
}

func (_c *InvitationService_DecideInvitationApproval_Call) Return(_a0 models.MembershipInvitation, _a1 error) *InvitationService_DecideInvitationApproval_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_DecideInvitationApproval_Call) RunAndReturn(run func(context.Context, models.DecideInvitationApprovalInput) (models.MembershipInvitation, error)) *InvitationService_DecideInvitationApproval_Call {
	_c.Call.Return(run)
	return _c
}

// DeclineInvitation provides a mock function with given fields: ctx, input
func (_m *InvitationService) DeclineInvitation(ctx context.Context, input models.DeclineInvitationInput) (models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeclineInvitation")
	}

	var r0 models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.DeclineInvitationInput) (models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.DeclineInvitationInput) models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.MembershipInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.DeclineInvitationInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_DeclineInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclineInvitation'
type InvitationService_DeclineInvitation_Call struct {
	*mock.Call
}

// DeclineInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.DeclineInvitationInput
func (_e *InvitationService_Expecter) DeclineInvitation(ctx interface{}, input interface{}) *InvitationService_DeclineInvitation_Call {
	return &InvitationService_DeclineInvitation_Call{Call: _e.mock.On("DeclineInvitation", ctx, input)}
}

func (_c *InvitationService_DeclineInvitation_Call) Run(run func(ctx context.Context, input models.DeclineInvitationInput)) *InvitationService_DeclineInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.DeclineInvitationInput))
	})
	return _c
}

func (_c *InvitationService_DeclineInvitation_Call) Return(_a0 models.MembershipInvitation, _a1 error) *InvitationService_DeclineInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_DeclineInvitation_Call) RunAndReturn(run func(context.Context, models.DeclineInvitationInput) (models.MembershipInvitation, error)) *InvitationService_DeclineInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// ListCompanyInvitations provides a mock function with given fields: ctx, input
func (_m *InvitationService) ListCompanyInvitations(ctx context.Context, input models.ListCompanyInvitationsInput) ([]models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListCompanyInvitations")
	}

	var r0 []models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListCompanyInvitationsInput) ([]models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListCompanyInvitationsInput) []models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MembershipInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListCompanyInvitationsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_ListCompanyInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompanyInvitations'
type InvitationService_ListCompanyInvitations_Call struct {
	*mock.Call
}

// ListCompanyInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListCompanyInvitationsInput
func (_e *InvitationService_Expecter) ListCompanyInvitations(ctx interface{}, input interface{}) *InvitationService_ListCompanyInvitations_Call {
	return &InvitationService_ListCompanyInvitations_Call{Call: _e.mock.On("ListCompanyInvitations", ctx, input)}
}

func (_c *InvitationService_ListCompanyInvitations_Call) Run(run func(ctx context.Context, input models.ListCompanyInvitationsInput)) *InvitationService_ListCompanyInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListCompanyInvitationsInput))
	})
	return _c
}

func (_c *InvitationService_ListCompanyInvitations_Call) Return(_a0 []models.MembershipInvitation, _a1 error) *InvitationService_ListCompanyInvitations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_ListCompanyInvitations_Call) RunAndReturn(run func(context.Context, models.ListCompanyInvitationsInput) ([]models.MembershipInvitation, error)) *InvitationService_ListCompanyInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserInvitations provides a mock function with given fields: ctx, input
func (_m *InvitationService) ListUserInvitations(ctx context.Context, input models.ListUserInvitationsInput) ([]models.MembershipInvitation, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListUserInvitations")
	}

	var r0 []models.MembershipInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListUserInvitationsInput) ([]models.MembershipInvitation, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListUserInvitationsInput) []models.MembershipInvitation); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MembershipInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListUserInvitationsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationService_ListUserInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserInvitations'
type InvitationService_ListUserInvitations_Call struct {
	*mock.Call
}

// ListUserInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListUserInvitationsInput
func (_e *InvitationService_Expecter) ListUserInvitations(ctx interface{}, input interface{}) *InvitationService_ListUserInvitations_Call {
	return &InvitationService_ListUserInvitations_Call{Call: _e.mock.On("ListUserInvitations", ctx, input)}
}

func (_c *InvitationService_ListUserInvitations_Call) Run(run func(ctx context.Context, input models.ListUserInvitationsInput)) *InvitationService_ListUserInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListUserInvitationsInput))
	})
	return _c
}

func (_c *InvitationService_ListUserInvitations_Call) Return(_a0 []models.MembershipInvitation, _a1 error) *InvitationService_ListUserInvitations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationService_ListUserInvitations_Call) RunAndReturn(run func(context.Context, models.ListUserInvitationsInput) ([]models.MembershipInvitation, error)) *InvitationService_ListUserInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationService creates a new instance of InvitationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationService {
	mock := &InvitationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
