// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "verbatrace/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ReportService is an autogenerated mock type for the ReportService type
type ReportService struct {
	mock.Mock
}

type ReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportService) EXPECT() *ReportService_Expecter {
	return &ReportService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *ReportService) Create(ctx context.Context, input models.CreateReportInput) (models.ReportExport, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.ReportExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateReportInput) (models.ReportExport, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateReportInput) models.ReportExport); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ReportExport)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateReportInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReportService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateReportInput
func (_e *ReportService_Expecter) Create(ctx interface{}, input interface{}) *ReportService_Create_Call {
	return &ReportService_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *ReportService_Create_Call) Run(run func(ctx context.Context, input models.CreateReportInput)) *ReportService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateReportInput))
	})
	return _c
}

func (_c *ReportService_Create_Call) Return(_a0 models.ReportExport, _a1 error) *ReportService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_Create_Call) RunAndReturn(run func(context.Context, models.CreateReportInput) (models.ReportExport, error)) *ReportService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGlobal provides a mock function with given fields: ctx, input
func (_m *ReportService) CreateGlobal(ctx context.Context, input models.CreateGlobalReportInput) (models.ReportExport, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateGlobal")
	}

	var r0 models.ReportExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateGlobalReportInput) (models.ReportExport, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateGlobalReportInput) models.ReportExport); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ReportExport)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateGlobalReportInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_CreateGlobal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGlobal'
type ReportService_CreateGlobal_Call struct {
	*mock.Call
}

// CreateGlobal is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateGlobalReportInput
func (_e *ReportService_Expecter) CreateGlobal(ctx interface{}, input interface{}) *ReportService_CreateGlobal_Call {
	return &ReportService_CreateGlobal_Call{Call: _e.mock.On("CreateGlobal", ctx, input)}
}

func (_c *ReportService_CreateGlobal_Call) Run(run func(ctx context.Context, input models.CreateGlobalReportInput)) *ReportService_CreateGlobal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateGlobalReportInput))
	})
	return _c
}

func (_c *ReportService_CreateGlobal_Call) Return(_a0 models.ReportExport, _a1 error) *ReportService_CreateGlobal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_CreateGlobal_Call) RunAndReturn(run func(context.Context, models.CreateGlobalReportInput) (models.ReportExport, error)) *ReportService_CreateGlobal_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, reportID, userID
func (_m *ReportService) Delete(ctx context.Context, reportID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, reportID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, reportID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReportService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReportService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID uuid.UUID
//   - userID uuid.UUID
func (_e *ReportService_Expecter) Delete(ctx interface{}, reportID interface{}, userID interface{}) *ReportService_Delete_Call {
	return &ReportService_Delete_Call{Call: _e.mock.On("Delete", ctx, reportID, userID)}
}

func (_c *ReportService_Delete_Call) Run(run func(ctx context.Context, reportID uuid.UUID, userID uuid.UUID)) *ReportService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ReportService_Delete_Call) Return(_a0 error) *ReportService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *ReportService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function with given fields: ctx, reportID, userID
func (_m *ReportService) GetFile(ctx context.Context, reportID uuid.UUID, userID uuid.UUID) (models.ReportFile, error) {
	ret := _m.Called(ctx, reportID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 models.ReportFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.ReportFile, error)); ok {
		return rf(ctx, reportID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.ReportFile); ok {
		r0 = rf(ctx, reportID, userID)
	} else {
		r0 = ret.Get(0).(models.ReportFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, reportID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type ReportService_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID uuid.UUID
//   - userID uuid.UUID
func (_e *ReportService_Expecter) GetFile(ctx interface{}, reportID interface{}, userID interface{}) *ReportService_GetFile_Call {
	return &ReportService_GetFile_Call{Call: _e.mock.On("GetFile", ctx, reportID, userID)}
}

func (_c *ReportService_GetFile_Call) Run(run func(ctx context.Context, reportID uuid.UUID, userID uuid.UUID)) *ReportService_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ReportService_GetFile_Call) Return(_a0 models.ReportFile, _a1 error) *ReportService_GetFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_GetFile_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.ReportFile, error)) *ReportService_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, input
func (_m *ReportService) List(ctx context.Context, input models.ListReportsInput) (models.ListReportsResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 models.ListReportsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListReportsInput) (models.ListReportsResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListReportsInput) models.ListReportsResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ListReportsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListReportsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ReportService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListReportsInput
func (_e *ReportService_Expecter) List(ctx interface{}, input interface{}) *ReportService_List_Call {
	return &ReportService_List_Call{Call: _e.mock.On("List", ctx, input)}
}

func (_c *ReportService_List_Call) Run(run func(ctx context.Context, input models.ListReportsInput)) *ReportService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListReportsInput))
	})
	return _c
}

func (_c *ReportService_List_Call) Return(_a0 models.ListReportsResult, _a1 error) *ReportService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_List_Call) RunAndReturn(run func(context.Context, models.ListReportsInput) (models.ListReportsResult, error)) *ReportService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCallUUID provides a mock function with given fields: ctx, callID, userID
func (_m *ReportService) ListByCallUUID(ctx context.Context, callID uuid.UUID, userID uuid.UUID) ([]models.ReportExport, error) {
	ret := _m.Called(ctx, callID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCallUUID")
	}

	var r0 []models.ReportExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.ReportExport, error)); ok {
		return rf(ctx, callID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.ReportExport); ok {
		r0 = rf(ctx, callID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ReportExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, callID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_ListByCallUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCallUUID'
type ReportService_ListByCallUUID_Call struct {
	*mock.Call
}

// ListByCallUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - callID uuid.UUID
//   - userID uuid.UUID
func (_e *ReportService_Expecter) ListByCallUUID(ctx interface{}, callID interface{}, userID interface{}) *ReportService_ListByCallUUID_Call {
	return &ReportService_ListByCallUUID_Call{Call: _e.mock.On("ListByCallUUID", ctx, callID, userID)}
}

func (_c *ReportService_ListByCallUUID_Call) Run(run func(ctx context.Context, callID uuid.UUID, userID uuid.UUID)) *ReportService_ListByCallUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ReportService_ListByCallUUID_Call) Return(_a0 []models.ReportExport, _a1 error) *ReportService_ListByCallUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_ListByCallUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.ReportExport, error)) *ReportService_ListByCallUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportService creates a new instance of ReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportService {
	mock := &ReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
