// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AnalysisService is an autogenerated mock type for the AnalysisService type
type AnalysisService struct {
	mock.Mock
}

type AnalysisService_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalysisService) EXPECT() *AnalysisService_Expecter {
	return &AnalysisService_Expecter{mock: &_m.Mock}
}

// AnalyzeCall provides a mock function with given fields: ctx, input
func (_m *AnalysisService) AnalyzeCall(ctx context.Context, input models.AnalyzeCallInput) (models.CallAnalysis, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeCall")
	}

	var r0 models.CallAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AnalyzeCallInput) (models.CallAnalysis, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AnalyzeCallInput) models.CallAnalysis); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CallAnalysis)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AnalyzeCallInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalysisService_AnalyzeCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeCall'
type AnalysisService_AnalyzeCall_Call struct {
	*mock.Call
}

// AnalyzeCall is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AnalyzeCallInput
func (_e *AnalysisService_Expecter) AnalyzeCall(ctx interface{}, input interface{}) *AnalysisService_AnalyzeCall_Call {
	return &AnalysisService_AnalyzeCall_Call{Call: _e.mock.On("AnalyzeCall", ctx, input)}
}

func (_c *AnalysisService_AnalyzeCall_Call) Run(run func(ctx context.Context, input models.AnalyzeCallInput)) *AnalysisService_AnalyzeCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AnalyzeCallInput))
	})
	return _c
}

func (_c *AnalysisService_AnalyzeCall_Call) Return(_a0 models.CallAnalysis, _a1 error) *AnalysisService_AnalyzeCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalysisService_AnalyzeCall_Call) RunAndReturn(run func(context.Context, models.AnalyzeCallInput) (models.CallAnalysis, error)) *AnalysisService_AnalyzeCall_Call {
	_c.Call.Return(run)
	return _c
}

// DecideRerun provides a mock function with given fields: ctx, input
func (_m *AnalysisService) DecideRerun(ctx context.Context, input models.DecideAnalysisRerunRequestInput) (models.AnalysisRerunRequest, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DecideRerun")
	}

	var r0 models.AnalysisRerunRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.DecideAnalysisRerunRequestInput) (models.AnalysisRerunRequest, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.DecideAnalysisRerunRequestInput) models.AnalysisRerunRequest); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AnalysisRerunRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.DecideAnalysisRerunRequestInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalysisService_DecideRerun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideRerun'
type AnalysisService_DecideRerun_Call struct {
	*mock.Call
}

// DecideRerun is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.DecideAnalysisRerunRequestInput
func (_e *AnalysisService_Expecter) DecideRerun(ctx interface{}, input interface{}) *AnalysisService_DecideRerun_Call {
	return &AnalysisService_DecideRerun_Call{Call: _e.mock.On("DecideRerun", ctx, input)}
}

func (_c *AnalysisService_DecideRerun_Call) Run(run func(ctx context.Context, input models.DecideAnalysisRerunRequestInput)) *AnalysisService_DecideRerun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.DecideAnalysisRerunRequestInput))
	})
	return _c
}

func (_c *AnalysisService_DecideRerun_Call) Return(_a0 models.AnalysisRerunRequest, _a1 error) *AnalysisService_DecideRerun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalysisService_DecideRerun_Call) RunAndReturn(run func(context.Context, models.DecideAnalysisRerunRequestInput) (models.AnalysisRerunRequest, error)) *AnalysisService_DecideRerun_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppliedInstruction provides a mock function with given fields: ctx, analysisID, versionID, userID
func (_m *AnalysisService) GetAppliedInstruction(ctx context.Context, analysisID uuid.UUID, versionID uuid.UUID, userID uuid.UUID) (models.AppliedInstruction, error) {
	ret := _m.Called(ctx, analysisID, versionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppliedInstruction")
	}

	var r0 models.AppliedInstruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (models.AppliedInstruction, error)); ok {
		return rf(ctx, analysisID, versionID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) models.AppliedInstruction); ok {
		r0 = rf(ctx, analysisID, versionID, userID)
	} else {
		r0 = ret.Get(0).(models.AppliedInstruction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, analysisID, versionID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalysisService_GetAppliedInstruction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppliedInstruction'
type AnalysisService_GetAppliedInstruction_Call struct {
	*mock.Call
}

// GetAppliedInstruction is a helper method to define mock.On call
//   - ctx context.Context
//   - analysisID uuid.UUID
//   - versionID uuid.UUID
//   - userID uuid.UUID
func (_e *AnalysisService_Expecter) GetAppliedInstruction(ctx interface{}, analysisID interface{}, versionID interface{}, userID interface{}) *AnalysisService_GetAppliedInstruction_Call {
	return &AnalysisService_GetAppliedInstruction_Call{Call: _e.mock.On("GetAppliedInstruction", ctx, analysisID, versionID, userID)}
}

func (_c *AnalysisService_GetAppliedInstruction_Call) Run(run func(ctx context.Context, analysisID uuid.UUID, versionID uuid.UUID, userID uuid.UUID)) *AnalysisService_GetAppliedInstruction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *AnalysisService_GetAppliedInstruction_Call) Return(_a0 models.AppliedInstruction, _a1 error) *AnalysisService_GetAppliedInstruction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalysisService_GetAppliedInstruction_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (models.AppliedInstruction, error)) *AnalysisService_GetAppliedInstruction_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCallUUID provides a mock function with given fields: ctx, callUUID, userID
func (_m *AnalysisService) GetByCallUUID(ctx context.Context, callUUID uuid.UUID, userID uuid.UUID) (models.CallAnalysis, error) {
	ret := _m.Called(ctx, callUUID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCallUUID")
	}

	var r0 models.CallAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.CallAnalysis, error)); ok {
		return rf(ctx, callUUID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.CallAnalysis); ok {
		r0 = rf(ctx, callUUID, userID)
	} else {
		r0 = ret.Get(0).(models.CallAnalysis)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, callUUID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalysisService_GetByCallUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCallUUID'
type AnalysisService_GetByCallUUID_Call struct {
	*mock.Call
}

// GetByCallUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - callUUID uuid.UUID
//   - userID uuid.UUID
func (_e *AnalysisService_Expecter) GetByCallUUID(ctx interface{}, callUUID interface{}, userID interface{}) *AnalysisService_GetByCallUUID_Call {
	return &AnalysisService_GetByCallUUID_Call{Call: _e.mock.On("GetByCallUUID", ctx, callUUID, userID)}
}

func (_c *AnalysisService_GetByCallUUID_Call) Run(run func(ctx context.Context, callUUID uuid.UUID, userID uuid.UUID)) *AnalysisService_GetByCallUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AnalysisService_GetByCallUUID_Call) Return(_a0 models.CallAnalysis, _a1 error) *AnalysisService_GetByCallUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalysisService_GetByCallUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.CallAnalysis, error)) *AnalysisService_GetByCallUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppliedInstructions provides a mock function with given fields: ctx, analysisID, userID
func (_m *AnalysisService) ListAppliedInstructions(ctx context.Context, analysisID uuid.UUID, userID uuid.UUID) ([]models.AppliedInstruction, error) {
	ret := _m.Called(ctx, analysisID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAppliedInstructions")
	}

	var r0 []models.AppliedInstruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.AppliedInstruction, error)); ok {
		return rf(ctx, analysisID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.AppliedInstruction); ok {
		r0 = rf(ctx, analysisID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AppliedInstruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, analysisID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalysisService_ListAppliedInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppliedInstructions'
type AnalysisService_ListAppliedInstructions_Call struct {
	*mock.Call
}

// ListAppliedInstructions is a helper method to define mock.On call
//   - ctx context.Context
//   - analysisID uuid.UUID
//   - userID uuid.UUID
func (_e *AnalysisService_Expecter) ListAppliedInstructions(ctx interface{}, analysisID interface{}, userID interface{}) *AnalysisService_ListAppliedInstructions_Call {
	return &AnalysisService_ListAppliedInstructions_Call{Call: _e.mock.On("ListAppliedInstructions", ctx, analysisID, userID)}
}

func (_c *AnalysisService_ListAppliedInstructions_Call) Run(run func(ctx context.Context, analysisID uuid.UUID, userID uuid.UUID)) *AnalysisService_ListAppliedInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AnalysisService_ListAppliedInstructions_Call) Return(_a0 []models.AppliedInstruction, _a1 error) *AnalysisService_ListAppliedInstructions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalysisService_ListAppliedInstructions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.AppliedInstruction, error)) *AnalysisService_ListAppliedInstructions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRerunRequests provides a mock function with given fields: ctx, input
func (_m *AnalysisService) ListRerunRequests(ctx context.Context, input models.ListAnalysisRerunRequestsInput) ([]models.AnalysisRerunRequest, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListRerunRequests")
	}

	var r0 []models.AnalysisRerunRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListAnalysisRerunRequestsInput) ([]models.AnalysisRerunRequest, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListAnalysisRerunRequestsInput) []models.AnalysisRerunRequest); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AnalysisRerunRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListAnalysisRerunRequestsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalysisService_ListRerunRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRerunRequests'
type AnalysisService_ListRerunRequests_Call struct {
	*mock.Call
}

// ListRerunRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListAnalysisRerunRequestsInput
func (_e *AnalysisService_Expecter) ListRerunRequests(ctx interface{}, input interface{}) *AnalysisService_ListRerunRequests_Call {
	return &AnalysisService_ListRerunRequests_Call{Call: _e.mock.On("ListRerunRequests", ctx, input)}
}

func (_c *AnalysisService_ListRerunRequests_Call) Run(run func(ctx context.Context, input models.ListAnalysisRerunRequestsInput)) *AnalysisService_ListRerunRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListAnalysisRerunRequestsInput))
	})
	return _c
}

func (_c *AnalysisService_ListRerunRequests_Call) Return(_a0 []models.AnalysisRerunRequest, _a1 error) *AnalysisService_ListRerunRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalysisService_ListRerunRequests_Call) RunAndReturn(run func(context.Context, models.ListAnalysisRerunRequestsInput) ([]models.AnalysisRerunRequest, error)) *AnalysisService_ListRerunRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRerun provides a mock function with given fields: ctx, input
func (_m *AnalysisService) RequestRerun(ctx context.Context, input models.CreateAnalysisRerunRequestInput) (models.AnalysisRerunRequest, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RequestRerun")
	}

	var r0 models.AnalysisRerunRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateAnalysisRerunRequestInput) (models.AnalysisRerunRequest, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateAnalysisRerunRequestInput) models.AnalysisRerunRequest); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AnalysisRerunRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateAnalysisRerunRequestInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalysisService_RequestRerun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRerun'
type AnalysisService_RequestRerun_Call struct {
	*mock.Call
}

// RequestRerun is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateAnalysisRerunRequestInput
func (_e *AnalysisService_Expecter) RequestRerun(ctx interface{}, input interface{}) *AnalysisService_RequestRerun_Call {
	return &AnalysisService_RequestRerun_Call{Call: _e.mock.On("RequestRerun", ctx, input)}
}

func (_c *AnalysisService_RequestRerun_Call) Run(run func(ctx context.Context, input models.CreateAnalysisRerunRequestInput)) *AnalysisService_RequestRerun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateAnalysisRerunRequestInput))
	})
	return _c
}

func (_c *AnalysisService_RequestRerun_Call) Return(_a0 models.AnalysisRerunRequest, _a1 error) *AnalysisService_RequestRerun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalysisService_RequestRerun_Call) RunAndReturn(run func(context.Context, models.CreateAnalysisRerunRequestInput) (models.AnalysisRerunRequest, error)) *AnalysisService_RequestRerun_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalysisService creates a new instance of AnalysisService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalysisService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalysisService {
	mock := &AnalysisService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
