// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// DeleteAvatar provides a mock function with given fields: ctx, userID
func (_m *AuthService) DeleteAvatar(ctx context.Context, userID uuid.UUID) (models.UserAvatarResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 models.UserAvatarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.UserAvatarResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.UserAvatarResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.UserAvatarResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_DeleteAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAvatar'
type AuthService_DeleteAvatar_Call struct {
	*mock.Call
}

// DeleteAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthService_Expecter) DeleteAvatar(ctx interface{}, userID interface{}) *AuthService_DeleteAvatar_Call {
	return &AuthService_DeleteAvatar_Call{Call: _e.mock.On("DeleteAvatar", ctx, userID)}
}

func (_c *AuthService_DeleteAvatar_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthService_DeleteAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_DeleteAvatar_Call) Return(_a0 models.UserAvatarResponse, _a1 error) *AuthService_DeleteAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_DeleteAvatar_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.UserAvatarResponse, error)) *AuthService_DeleteAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatar provides a mock function with given fields: ctx, userID
func (_m *AuthService) GetAvatar(ctx context.Context, userID uuid.UUID) (models.File, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatar")
	}

	var r0 models.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.File, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.File); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.File)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_GetAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatar'
type AuthService_GetAvatar_Call struct {
	*mock.Call
}

// GetAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthService_Expecter) GetAvatar(ctx interface{}, userID interface{}) *AuthService_GetAvatar_Call {
	return &AuthService_GetAvatar_Call{Call: _e.mock.On("GetAvatar", ctx, userID)}
}

func (_c *AuthService_GetAvatar_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthService_GetAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_GetAvatar_Call) Return(_a0 models.File, _a1 error) *AuthService_GetAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_GetAvatar_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.File, error)) *AuthService_GetAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreferences provides a mock function with given fields: ctx, userID
func (_m *AuthService) GetPreferences(ctx context.Context, userID uuid.UUID) (models.UserPreferences, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 models.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.UserPreferences, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.UserPreferences); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.UserPreferences)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_GetPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreferences'
type AuthService_GetPreferences_Call struct {
	*mock.Call
}

// GetPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthService_Expecter) GetPreferences(ctx interface{}, userID interface{}) *AuthService_GetPreferences_Call {
	return &AuthService_GetPreferences_Call{Call: _e.mock.On("GetPreferences", ctx, userID)}
}

func (_c *AuthService_GetPreferences_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthService_GetPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_GetPreferences_Call) Return(_a0 models.UserPreferences, _a1 error) *AuthService_GetPreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_GetPreferences_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.UserPreferences, error)) *AuthService_GetPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *AuthService) GetUserByUsername(ctx context.Context, username string) (models.CurrentUser, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 models.CurrentUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.CurrentUser, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.CurrentUser); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(models.CurrentUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type AuthService_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *AuthService_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *AuthService_GetUserByUsername_Call {
	return &AuthService_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *AuthService_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *AuthService_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_GetUserByUsername_Call) Return(_a0 models.CurrentUser, _a1 error) *AuthService_GetUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_GetUserByUsername_Call) RunAndReturn(run func(context.Context, string) (models.CurrentUser, error)) *AuthService_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx, userID, currentSessionID
func (_m *AuthService) ListSessions(ctx context.Context, userID uuid.UUID, currentSessionID uuid.UUID) ([]models.UserSession, error) {
	ret := _m.Called(ctx, userID, currentSessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []models.UserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.UserSession, error)); ok {
		return rf(ctx, userID, currentSessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.UserSession); ok {
		r0 = rf(ctx, userID, currentSessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, currentSessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type AuthService_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currentSessionID uuid.UUID
func (_e *AuthService_Expecter) ListSessions(ctx interface{}, userID interface{}, currentSessionID interface{}) *AuthService_ListSessions_Call {
	return &AuthService_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, userID, currentSessionID)}
}

func (_c *AuthService_ListSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID, currentSessionID uuid.UUID)) *AuthService_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_ListSessions_Call) Return(_a0 []models.UserSession, _a1 error) *AuthService_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_ListSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.UserSession, error)) *AuthService_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, input
func (_m *AuthService) Login(ctx context.Context, input models.LoginInput) (models.CurrentUser, string, string, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 models.CurrentUser
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, models.LoginInput) (models.CurrentUser, string, string, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.LoginInput) models.CurrentUser); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CurrentUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.LoginInput) string); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.LoginInput) string); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, models.LoginInput) error); ok {
		r3 = rf(ctx, input)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.LoginInput
func (_e *AuthService_Expecter) Login(ctx interface{}, input interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, input models.LoginInput)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.LoginInput))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 models.CurrentUser, _a1 string, _a2 string, _a3 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(context.Context, models.LoginInput) (models.CurrentUser, string, string, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, sessionID
func (_m *AuthService) Logout(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *AuthService_Expecter) Logout(ctx interface{}, sessionID interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionID)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(_a0 error) *AuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: ctx, userID, currentSessionID
func (_m *AuthService) LogoutAll(ctx context.Context, userID uuid.UUID, currentSessionID uuid.UUID) error {
	ret := _m.Called(ctx, userID, currentSessionID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, currentSessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type AuthService_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currentSessionID uuid.UUID
func (_e *AuthService_Expecter) LogoutAll(ctx interface{}, userID interface{}, currentSessionID interface{}) *AuthService_LogoutAll_Call {
	return &AuthService_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, userID, currentSessionID)}
}

func (_c *AuthService_LogoutAll_Call) Run(run func(ctx context.Context, userID uuid.UUID, currentSessionID uuid.UUID)) *AuthService_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_LogoutAll_Call) Return(_a0 error) *AuthService_LogoutAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_LogoutAll_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *AuthService_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function with given fields: ctx, userID
func (_m *AuthService) Me(ctx context.Context, userID uuid.UUID) (models.CurrentUser, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 models.CurrentUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.CurrentUser, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.CurrentUser); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.CurrentUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type AuthService_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthService_Expecter) Me(ctx interface{}, userID interface{}) *AuthService_Me_Call {
	return &AuthService_Me_Call{Call: _e.mock.On("Me", ctx, userID)}
}

func (_c *AuthService_Me_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthService_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_Me_Call) Return(_a0 models.CurrentUser, _a1 error) *AuthService_Me_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Me_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.CurrentUser, error)) *AuthService_Me_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, input
func (_m *AuthService) Refresh(ctx context.Context, input models.RefreshTokenInput) (models.CurrentUser, string, string, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 models.CurrentUser
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RefreshTokenInput) (models.CurrentUser, string, string, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.RefreshTokenInput) models.CurrentUser); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CurrentUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.RefreshTokenInput) string); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.RefreshTokenInput) string); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, models.RefreshTokenInput) error); ok {
		r3 = rf(ctx, input)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// AuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.RefreshTokenInput
func (_e *AuthService_Expecter) Refresh(ctx interface{}, input interface{}) *AuthService_Refresh_Call {
	return &AuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, input)}
}

func (_c *AuthService_Refresh_Call) Run(run func(ctx context.Context, input models.RefreshTokenInput)) *AuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RefreshTokenInput))
	})
	return _c
}

func (_c *AuthService_Refresh_Call) Return(_a0 models.CurrentUser, _a1 string, _a2 string, _a3 error) *AuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *AuthService_Refresh_Call) RunAndReturn(run func(context.Context, models.RefreshTokenInput) (models.CurrentUser, string, string, error)) *AuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, input
func (_m *AuthService) Register(ctx context.Context, input models.CreateUserInput) (models.CurrentUser, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 models.CurrentUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateUserInput) (models.CurrentUser, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateUserInput) models.CurrentUser); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CurrentUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateUserInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateUserInput
func (_e *AuthService_Expecter) Register(ctx interface{}, input interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, input)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, input models.CreateUserInput)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateUserInput))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 models.CurrentUser, _a1 error) *AuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(context.Context, models.CreateUserInput) (models.CurrentUser, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, userID, currentSessionID, sessionID
func (_m *AuthService) RevokeSession(ctx context.Context, userID uuid.UUID, currentSessionID uuid.UUID, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, userID, currentSessionID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, currentSessionID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type AuthService_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currentSessionID uuid.UUID
//   - sessionID uuid.UUID
func (_e *AuthService_Expecter) RevokeSession(ctx interface{}, userID interface{}, currentSessionID interface{}, sessionID interface{}) *AuthService_RevokeSession_Call {
	return &AuthService_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, userID, currentSessionID, sessionID)}
}

func (_c *AuthService_RevokeSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, currentSessionID uuid.UUID, sessionID uuid.UUID)) *AuthService_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *AuthService_RevokeSession_Call) Return(_a0 error) *AuthService_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_RevokeSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *AuthService_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, input
func (_m *AuthService) UpdatePassword(ctx context.Context, input models.UpdatePasswordInput) (models.UpdatePasswordResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 models.UpdatePasswordResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdatePasswordInput) (models.UpdatePasswordResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdatePasswordInput) models.UpdatePasswordResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.UpdatePasswordResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdatePasswordInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type AuthService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdatePasswordInput
func (_e *AuthService_Expecter) UpdatePassword(ctx interface{}, input interface{}) *AuthService_UpdatePassword_Call {
	return &AuthService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, input)}
}

func (_c *AuthService_UpdatePassword_Call) Run(run func(ctx context.Context, input models.UpdatePasswordInput)) *AuthService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdatePasswordInput))
	})
	return _c
}

func (_c *AuthService_UpdatePassword_Call) Return(_a0 models.UpdatePasswordResult, _a1 error) *AuthService_UpdatePassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_UpdatePassword_Call) RunAndReturn(run func(context.Context, models.UpdatePasswordInput) (models.UpdatePasswordResult, error)) *AuthService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePreferences provides a mock function with given fields: ctx, input
func (_m *AuthService) UpdatePreferences(ctx context.Context, input models.UpdateUserPreferencesInput) (models.UserPreferences, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 models.UserPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUserPreferencesInput) (models.UserPreferences, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUserPreferencesInput) models.UserPreferences); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.UserPreferences)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateUserPreferencesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_UpdatePreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePreferences'
type AuthService_UpdatePreferences_Call struct {
	*mock.Call
}

// UpdatePreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateUserPreferencesInput
func (_e *AuthService_Expecter) UpdatePreferences(ctx interface{}, input interface{}) *AuthService_UpdatePreferences_Call {
	return &AuthService_UpdatePreferences_Call{Call: _e.mock.On("UpdatePreferences", ctx, input)}
}

func (_c *AuthService_UpdatePreferences_Call) Run(run func(ctx context.Context, input models.UpdateUserPreferencesInput)) *AuthService_UpdatePreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateUserPreferencesInput))
	})
	return _c
}

func (_c *AuthService_UpdatePreferences_Call) Return(_a0 models.UserPreferences, _a1 error) *AuthService_UpdatePreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_UpdatePreferences_Call) RunAndReturn(run func(context.Context, models.UpdateUserPreferencesInput) (models.UserPreferences, error)) *AuthService_UpdatePreferences_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, input
func (_m *AuthService) UpdateProfile(ctx context.Context, input models.UpdateUserProfileInput) (models.CurrentUser, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 models.CurrentUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUserProfileInput) (models.CurrentUser, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUserProfileInput) models.CurrentUser); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CurrentUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateUserProfileInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type AuthService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateUserProfileInput
func (_e *AuthService_Expecter) UpdateProfile(ctx interface{}, input interface{}) *AuthService_UpdateProfile_Call {
	return &AuthService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, input)}
}

func (_c *AuthService_UpdateProfile_Call) Run(run func(ctx context.Context, input models.UpdateUserProfileInput)) *AuthService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateUserProfileInput))
	})
	return _c
}

func (_c *AuthService_UpdateProfile_Call) Return(_a0 models.CurrentUser, _a1 error) *AuthService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_UpdateProfile_Call) RunAndReturn(run func(context.Context, models.UpdateUserProfileInput) (models.CurrentUser, error)) *AuthService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUsername provides a mock function with given fields: ctx, input
func (_m *AuthService) UpdateUsername(ctx context.Context, input models.UpdateUsernameInput) (models.CurrentUser, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUsername")
	}

	var r0 models.CurrentUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUsernameInput) (models.CurrentUser, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateUsernameInput) models.CurrentUser); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CurrentUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateUsernameInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_UpdateUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUsername'
type AuthService_UpdateUsername_Call struct {
	*mock.Call
}

// UpdateUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateUsernameInput
func (_e *AuthService_Expecter) UpdateUsername(ctx interface{}, input interface{}) *AuthService_UpdateUsername_Call {
	return &AuthService_UpdateUsername_Call{Call: _e.mock.On("UpdateUsername", ctx, input)}
}

func (_c *AuthService_UpdateUsername_Call) Run(run func(ctx context.Context, input models.UpdateUsernameInput)) *AuthService_UpdateUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateUsernameInput))
	})
	return _c
}

func (_c *AuthService_UpdateUsername_Call) Return(_a0 models.CurrentUser, _a1 error) *AuthService_UpdateUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_UpdateUsername_Call) RunAndReturn(run func(context.Context, models.UpdateUsernameInput) (models.CurrentUser, error)) *AuthService_UpdateUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAvatar provides a mock function with given fields: ctx, input
func (_m *AuthService) UploadAvatar(ctx context.Context, input models.SaveUserAvatarInput) (models.UserAvatarResponse, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 models.UserAvatarResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SaveUserAvatarInput) (models.UserAvatarResponse, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.SaveUserAvatarInput) models.UserAvatarResponse); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.UserAvatarResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.SaveUserAvatarInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_UploadAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAvatar'
type AuthService_UploadAvatar_Call struct {
	*mock.Call
}

// UploadAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.SaveUserAvatarInput
func (_e *AuthService_Expecter) UploadAvatar(ctx interface{}, input interface{}) *AuthService_UploadAvatar_Call {
	return &AuthService_UploadAvatar_Call{Call: _e.mock.On("UploadAvatar", ctx, input)}
}

func (_c *AuthService_UploadAvatar_Call) Run(run func(ctx context.Context, input models.SaveUserAvatarInput)) *AuthService_UploadAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.SaveUserAvatarInput))
	})
	return _c
}

func (_c *AuthService_UploadAvatar_Call) Return(_a0 models.UserAvatarResponse, _a1 error) *AuthService_UploadAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_UploadAvatar_Call) RunAndReturn(run func(context.Context, models.SaveUserAvatarInput) (models.UserAvatarResponse, error)) *AuthService_UploadAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
