with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: false
issue-845-fix: true

packages:
  "verbatrace/monolit/internal/API":
    config:
      include-regex: ".*API"
  "verbatrace/monolit/internal/repository":
    config:
      include-regex: ".*Repository"
  "verbatrace/monolit/internal/service":
    config:
      include-regex: ".*Service"
  "verbatrace/monolit/internal/storage":
    config:
      include-regex: "Storage"
  "verbatrace/monolit/internal/analyzer":
    config:
      include-regex: "Analyzer"
  "verbatrace/monolit/internal/transcriber":
    config:
      include-regex: "Transcriber"
  "verbatrace/monolit/internal/service/processing":
    config:
      include-regex: "AnalysisProcessor"
  "verbatrace/monolit/internal/service/call":
    config:
      include-regex: "DurationDetector|BillingLimiter"
  "verbatrace/monolit/internal/service/report":
    config:
      include-regex: "BillingLimiter"
  "verbatrace/monolit/internal/service/analysis_instruction":
    config:
      include-regex: "BillingLimiter"
  "verbatrace/monolit/internal/service/billing":
    config:
      include-regex: "Repository|CompanyRepository"
  "verbatrace/monolit/internal/service/invitation":
    config:
      include-regex: "BillingLimiter"
