// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CompanyAPI is an autogenerated mock type for the CompanyAPI type
type CompanyAPI struct {
	mock.Mock
}

type CompanyAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyAPI) EXPECT() *CompanyAPI_Expecter {
	return &CompanyAPI_Expecter{mock: &_m.Mock}
}

// AcceptOwnership provides a mock function with given fields: w, r
func (_m *CompanyAPI) AcceptOwnership(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_AcceptOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptOwnership'
type CompanyAPI_AcceptOwnership_Call struct {
	*mock.Call
}

// AcceptOwnership is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) AcceptOwnership(w interface{}, r interface{}) *CompanyAPI_AcceptOwnership_Call {
	return &CompanyAPI_AcceptOwnership_Call{Call: _e.mock.On("AcceptOwnership", w, r)}
}

func (_c *CompanyAPI_AcceptOwnership_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_AcceptOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_AcceptOwnership_Call) Return() *CompanyAPI_AcceptOwnership_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_AcceptOwnership_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_AcceptOwnership_Call {
	_c.Run(run)
	return _c
}

// ActivateCompany provides a mock function with given fields: w, r
func (_m *CompanyAPI) ActivateCompany(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_ActivateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateCompany'
type CompanyAPI_ActivateCompany_Call struct {
	*mock.Call
}

// ActivateCompany is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) ActivateCompany(w interface{}, r interface{}) *CompanyAPI_ActivateCompany_Call {
	return &CompanyAPI_ActivateCompany_Call{Call: _e.mock.On("ActivateCompany", w, r)}
}

func (_c *CompanyAPI_ActivateCompany_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_ActivateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_ActivateCompany_Call) Return() *CompanyAPI_ActivateCompany_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_ActivateCompany_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_ActivateCompany_Call {
	_c.Run(run)
	return _c
}

// CancelCompanyDeletion provides a mock function with given fields: w, r
func (_m *CompanyAPI) CancelCompanyDeletion(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_CancelCompanyDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelCompanyDeletion'
type CompanyAPI_CancelCompanyDeletion_Call struct {
	*mock.Call
}

// CancelCompanyDeletion is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) CancelCompanyDeletion(w interface{}, r interface{}) *CompanyAPI_CancelCompanyDeletion_Call {
	return &CompanyAPI_CancelCompanyDeletion_Call{Call: _e.mock.On("CancelCompanyDeletion", w, r)}
}

func (_c *CompanyAPI_CancelCompanyDeletion_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_CancelCompanyDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_CancelCompanyDeletion_Call) Return() *CompanyAPI_CancelCompanyDeletion_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_CancelCompanyDeletion_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_CancelCompanyDeletion_Call {
	_c.Run(run)
	return _c
}

// CancelOwnershipOffer provides a mock function with given fields: w, r
func (_m *CompanyAPI) CancelOwnershipOffer(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_CancelOwnershipOffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOwnershipOffer'
type CompanyAPI_CancelOwnershipOffer_Call struct {
	*mock.Call
}

// CancelOwnershipOffer is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) CancelOwnershipOffer(w interface{}, r interface{}) *CompanyAPI_CancelOwnershipOffer_Call {
	return &CompanyAPI_CancelOwnershipOffer_Call{Call: _e.mock.On("CancelOwnershipOffer", w, r)}
}

func (_c *CompanyAPI_CancelOwnershipOffer_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_CancelOwnershipOffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_CancelOwnershipOffer_Call) Return() *CompanyAPI_CancelOwnershipOffer_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_CancelOwnershipOffer_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_CancelOwnershipOffer_Call {
	_c.Run(run)
	return _c
}

// Create provides a mock function with given fields: w, r
func (_m *CompanyAPI) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CompanyAPI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) Create(w interface{}, r interface{}) *CompanyAPI_Create_Call {
	return &CompanyAPI_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *CompanyAPI_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_Create_Call) Return() *CompanyAPI_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_Create_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_Create_Call {
	_c.Run(run)
	return _c
}

// DeclineOwnership provides a mock function with given fields: w, r
func (_m *CompanyAPI) DeclineOwnership(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_DeclineOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclineOwnership'
type CompanyAPI_DeclineOwnership_Call struct {
	*mock.Call
}

// DeclineOwnership is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) DeclineOwnership(w interface{}, r interface{}) *CompanyAPI_DeclineOwnership_Call {
	return &CompanyAPI_DeclineOwnership_Call{Call: _e.mock.On("DeclineOwnership", w, r)}
}

func (_c *CompanyAPI_DeclineOwnership_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_DeclineOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_DeclineOwnership_Call) Return() *CompanyAPI_DeclineOwnership_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_DeclineOwnership_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_DeclineOwnership_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function with given fields: w, r
func (_m *CompanyAPI) Delete(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CompanyAPI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) Delete(w interface{}, r interface{}) *CompanyAPI_Delete_Call {
	return &CompanyAPI_Delete_Call{Call: _e.mock.On("Delete", w, r)}
}

func (_c *CompanyAPI_Delete_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_Delete_Call) Return() *CompanyAPI_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_Delete_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_Delete_Call {
	_c.Run(run)
	return _c
}

// FreezeCompany provides a mock function with given fields: w, r
func (_m *CompanyAPI) FreezeCompany(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_FreezeCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FreezeCompany'
type CompanyAPI_FreezeCompany_Call struct {
	*mock.Call
}

// FreezeCompany is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) FreezeCompany(w interface{}, r interface{}) *CompanyAPI_FreezeCompany_Call {
	return &CompanyAPI_FreezeCompany_Call{Call: _e.mock.On("FreezeCompany", w, r)}
}

func (_c *CompanyAPI_FreezeCompany_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_FreezeCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_FreezeCompany_Call) Return() *CompanyAPI_FreezeCompany_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_FreezeCompany_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_FreezeCompany_Call {
	_c.Run(run)
	return _c
}

// GetByUUID provides a mock function with given fields: w, r
func (_m *CompanyAPI) GetByUUID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type CompanyAPI_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) GetByUUID(w interface{}, r interface{}) *CompanyAPI_GetByUUID_Call {
	return &CompanyAPI_GetByUUID_Call{Call: _e.mock.On("GetByUUID", w, r)}
}

func (_c *CompanyAPI_GetByUUID_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_GetByUUID_Call) Return() *CompanyAPI_GetByUUID_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_GetByUUID_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_GetByUUID_Call {
	_c.Run(run)
	return _c
}

// GetCompanyLifecycle provides a mock function with given fields: w, r
func (_m *CompanyAPI) GetCompanyLifecycle(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_GetCompanyLifecycle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyLifecycle'
type CompanyAPI_GetCompanyLifecycle_Call struct {
	*mock.Call
}

// GetCompanyLifecycle is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) GetCompanyLifecycle(w interface{}, r interface{}) *CompanyAPI_GetCompanyLifecycle_Call {
	return &CompanyAPI_GetCompanyLifecycle_Call{Call: _e.mock.On("GetCompanyLifecycle", w, r)}
}

func (_c *CompanyAPI_GetCompanyLifecycle_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_GetCompanyLifecycle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_GetCompanyLifecycle_Call) Return() *CompanyAPI_GetCompanyLifecycle_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_GetCompanyLifecycle_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_GetCompanyLifecycle_Call {
	_c.Run(run)
	return _c
}

// GetCompanyMembersOverview provides a mock function with given fields: w, r
func (_m *CompanyAPI) GetCompanyMembersOverview(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_GetCompanyMembersOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyMembersOverview'
type CompanyAPI_GetCompanyMembersOverview_Call struct {
	*mock.Call
}

// GetCompanyMembersOverview is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) GetCompanyMembersOverview(w interface{}, r interface{}) *CompanyAPI_GetCompanyMembersOverview_Call {
	return &CompanyAPI_GetCompanyMembersOverview_Call{Call: _e.mock.On("GetCompanyMembersOverview", w, r)}
}

func (_c *CompanyAPI_GetCompanyMembersOverview_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_GetCompanyMembersOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_GetCompanyMembersOverview_Call) Return() *CompanyAPI_GetCompanyMembersOverview_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_GetCompanyMembersOverview_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_GetCompanyMembersOverview_Call {
	_c.Run(run)
	return _c
}

// LeaveCompany provides a mock function with given fields: w, r
func (_m *CompanyAPI) LeaveCompany(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_LeaveCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveCompany'
type CompanyAPI_LeaveCompany_Call struct {
	*mock.Call
}

// LeaveCompany is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) LeaveCompany(w interface{}, r interface{}) *CompanyAPI_LeaveCompany_Call {
	return &CompanyAPI_LeaveCompany_Call{Call: _e.mock.On("LeaveCompany", w, r)}
}

func (_c *CompanyAPI_LeaveCompany_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_LeaveCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_LeaveCompany_Call) Return() *CompanyAPI_LeaveCompany_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_LeaveCompany_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_LeaveCompany_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function with given fields: w, r
func (_m *CompanyAPI) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CompanyAPI_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) List(w interface{}, r interface{}) *CompanyAPI_List_Call {
	return &CompanyAPI_List_Call{Call: _e.mock.On("List", w, r)}
}

func (_c *CompanyAPI_List_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_List_Call) Return() *CompanyAPI_List_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_List_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_List_Call {
	_c.Run(run)
	return _c
}

// ListIncomingOwnership provides a mock function with given fields: w, r
func (_m *CompanyAPI) ListIncomingOwnership(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_ListIncomingOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIncomingOwnership'
type CompanyAPI_ListIncomingOwnership_Call struct {
	*mock.Call
}

// ListIncomingOwnership is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) ListIncomingOwnership(w interface{}, r interface{}) *CompanyAPI_ListIncomingOwnership_Call {
	return &CompanyAPI_ListIncomingOwnership_Call{Call: _e.mock.On("ListIncomingOwnership", w, r)}
}

func (_c *CompanyAPI_ListIncomingOwnership_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_ListIncomingOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_ListIncomingOwnership_Call) Return() *CompanyAPI_ListIncomingOwnership_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_ListIncomingOwnership_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_ListIncomingOwnership_Call {
	_c.Run(run)
	return _c
}

// OfferAllOwnership provides a mock function with given fields: w, r
func (_m *CompanyAPI) OfferAllOwnership(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_OfferAllOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OfferAllOwnership'
type CompanyAPI_OfferAllOwnership_Call struct {
	*mock.Call
}

// OfferAllOwnership is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) OfferAllOwnership(w interface{}, r interface{}) *CompanyAPI_OfferAllOwnership_Call {
	return &CompanyAPI_OfferAllOwnership_Call{Call: _e.mock.On("OfferAllOwnership", w, r)}
}

func (_c *CompanyAPI_OfferAllOwnership_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_OfferAllOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_OfferAllOwnership_Call) Return() *CompanyAPI_OfferAllOwnership_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_OfferAllOwnership_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_OfferAllOwnership_Call {
	_c.Run(run)
	return _c
}

// OfferOwnership provides a mock function with given fields: w, r
func (_m *CompanyAPI) OfferOwnership(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_OfferOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OfferOwnership'
type CompanyAPI_OfferOwnership_Call struct {
	*mock.Call
}

// OfferOwnership is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) OfferOwnership(w interface{}, r interface{}) *CompanyAPI_OfferOwnership_Call {
	return &CompanyAPI_OfferOwnership_Call{Call: _e.mock.On("OfferOwnership", w, r)}
}

func (_c *CompanyAPI_OfferOwnership_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_OfferOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_OfferOwnership_Call) Return() *CompanyAPI_OfferOwnership_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_OfferOwnership_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_OfferOwnership_Call {
	_c.Run(run)
	return _c
}

// RemoveCompanyMember provides a mock function with given fields: w, r
func (_m *CompanyAPI) RemoveCompanyMember(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_RemoveCompanyMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCompanyMember'
type CompanyAPI_RemoveCompanyMember_Call struct {
	*mock.Call
}

// RemoveCompanyMember is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) RemoveCompanyMember(w interface{}, r interface{}) *CompanyAPI_RemoveCompanyMember_Call {
	return &CompanyAPI_RemoveCompanyMember_Call{Call: _e.mock.On("RemoveCompanyMember", w, r)}
}

func (_c *CompanyAPI_RemoveCompanyMember_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_RemoveCompanyMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_RemoveCompanyMember_Call) Return() *CompanyAPI_RemoveCompanyMember_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_RemoveCompanyMember_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_RemoveCompanyMember_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function with given fields: w, r
func (_m *CompanyAPI) Update(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CompanyAPI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) Update(w interface{}, r interface{}) *CompanyAPI_Update_Call {
	return &CompanyAPI_Update_Call{Call: _e.mock.On("Update", w, r)}
}

func (_c *CompanyAPI_Update_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_Update_Call) Return() *CompanyAPI_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_Update_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_Update_Call {
	_c.Run(run)
	return _c
}

// UpdateCompanyMemberJobTitle provides a mock function with given fields: w, r
func (_m *CompanyAPI) UpdateCompanyMemberJobTitle(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_UpdateCompanyMemberJobTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompanyMemberJobTitle'
type CompanyAPI_UpdateCompanyMemberJobTitle_Call struct {
	*mock.Call
}

// UpdateCompanyMemberJobTitle is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) UpdateCompanyMemberJobTitle(w interface{}, r interface{}) *CompanyAPI_UpdateCompanyMemberJobTitle_Call {
	return &CompanyAPI_UpdateCompanyMemberJobTitle_Call{Call: _e.mock.On("UpdateCompanyMemberJobTitle", w, r)}
}

func (_c *CompanyAPI_UpdateCompanyMemberJobTitle_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_UpdateCompanyMemberJobTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_UpdateCompanyMemberJobTitle_Call) Return() *CompanyAPI_UpdateCompanyMemberJobTitle_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_UpdateCompanyMemberJobTitle_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_UpdateCompanyMemberJobTitle_Call {
	_c.Run(run)
	return _c
}

// UpdateCompanyMemberRole provides a mock function with given fields: w, r
func (_m *CompanyAPI) UpdateCompanyMemberRole(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_UpdateCompanyMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompanyMemberRole'
type CompanyAPI_UpdateCompanyMemberRole_Call struct {
	*mock.Call
}

// UpdateCompanyMemberRole is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) UpdateCompanyMemberRole(w interface{}, r interface{}) *CompanyAPI_UpdateCompanyMemberRole_Call {
	return &CompanyAPI_UpdateCompanyMemberRole_Call{Call: _e.mock.On("UpdateCompanyMemberRole", w, r)}
}

func (_c *CompanyAPI_UpdateCompanyMemberRole_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_UpdateCompanyMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_UpdateCompanyMemberRole_Call) Return() *CompanyAPI_UpdateCompanyMemberRole_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_UpdateCompanyMemberRole_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_UpdateCompanyMemberRole_Call {
	_c.Run(run)
	return _c
}

// UpdateTag provides a mock function with given fields: w, r
func (_m *CompanyAPI) UpdateTag(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_UpdateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTag'
type CompanyAPI_UpdateTag_Call struct {
	*mock.Call
}

// UpdateTag is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) UpdateTag(w interface{}, r interface{}) *CompanyAPI_UpdateTag_Call {
	return &CompanyAPI_UpdateTag_Call{Call: _e.mock.On("UpdateTag", w, r)}
}

func (_c *CompanyAPI_UpdateTag_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_UpdateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_UpdateTag_Call) Return() *CompanyAPI_UpdateTag_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_UpdateTag_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_UpdateTag_Call {
	_c.Run(run)
	return _c
}

// UpdateTagAsAdmin provides a mock function with given fields: w, r
func (_m *CompanyAPI) UpdateTagAsAdmin(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CompanyAPI_UpdateTagAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTagAsAdmin'
type CompanyAPI_UpdateTagAsAdmin_Call struct {
	*mock.Call
}

// UpdateTagAsAdmin is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *CompanyAPI_Expecter) UpdateTagAsAdmin(w interface{}, r interface{}) *CompanyAPI_UpdateTagAsAdmin_Call {
	return &CompanyAPI_UpdateTagAsAdmin_Call{Call: _e.mock.On("UpdateTagAsAdmin", w, r)}
}

func (_c *CompanyAPI_UpdateTagAsAdmin_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *CompanyAPI_UpdateTagAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *CompanyAPI_UpdateTagAsAdmin_Call) Return() *CompanyAPI_UpdateTagAsAdmin_Call {
	_c.Call.Return()
	return _c
}

func (_c *CompanyAPI_UpdateTagAsAdmin_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *CompanyAPI_UpdateTagAsAdmin_Call {
	_c.Run(run)
	return _c
}

// NewCompanyAPI creates a new instance of CompanyAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyAPI {
	mock := &CompanyAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
