// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AnalyticsAPI is an autogenerated mock type for the AnalyticsAPI type
type AnalyticsAPI struct {
	mock.Mock
}

type AnalyticsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalyticsAPI) EXPECT() *AnalyticsAPI_Expecter {
	return &AnalyticsAPI_Expecter{mock: &_m.Mock}
}

// GetOverview provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) GetOverview(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type AnalyticsAPI_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) GetOverview(w interface{}, r interface{}) *AnalyticsAPI_GetOverview_Call {
	return &AnalyticsAPI_GetOverview_Call{Call: _e.mock.On("GetOverview", w, r)}
}

func (_c *AnalyticsAPI_GetOverview_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_GetOverview_Call) Return() *AnalyticsAPI_GetOverview_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_GetOverview_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_GetOverview_Call {
	_c.Run(run)
	return _c
}

// NewAnalyticsAPI creates a new instance of AnalyticsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsAPI {
	mock := &AnalyticsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
