// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IntegrationAPI is an autogenerated mock type for the IntegrationAPI type
type IntegrationAPI struct {
	mock.Mock
}

type IntegrationAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *IntegrationAPI) EXPECT() *IntegrationAPI_Expecter {
	return &IntegrationAPI_Expecter{mock: &_m.Mock}
}

// CancelIngestItem provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) CancelIngestItem(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_CancelIngestItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelIngestItem'
type IntegrationAPI_CancelIngestItem_Call struct {
	*mock.Call
}

// CancelIngestItem is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) CancelIngestItem(_a0 interface{}, _a1 interface{}) *IntegrationAPI_CancelIngestItem_Call {
	return &IntegrationAPI_CancelIngestItem_Call{Call: _e.mock.On("CancelIngestItem", _a0, _a1)}
}

func (_c *IntegrationAPI_CancelIngestItem_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_CancelIngestItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_CancelIngestItem_Call) Return() *IntegrationAPI_CancelIngestItem_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_CancelIngestItem_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_CancelIngestItem_Call {
	_c.Run(run)
	return _c
}

// CreateConnection provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) CreateConnection(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_CreateConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnection'
type IntegrationAPI_CreateConnection_Call struct {
	*mock.Call
}

// CreateConnection is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) CreateConnection(_a0 interface{}, _a1 interface{}) *IntegrationAPI_CreateConnection_Call {
	return &IntegrationAPI_CreateConnection_Call{Call: _e.mock.On("CreateConnection", _a0, _a1)}
}

func (_c *IntegrationAPI_CreateConnection_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_CreateConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_CreateConnection_Call) Return() *IntegrationAPI_CreateConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_CreateConnection_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_CreateConnection_Call {
	_c.Run(run)
	return _c
}

// CreateWebhook provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) CreateWebhook(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_CreateWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebhook'
type IntegrationAPI_CreateWebhook_Call struct {
	*mock.Call
}

// CreateWebhook is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) CreateWebhook(_a0 interface{}, _a1 interface{}) *IntegrationAPI_CreateWebhook_Call {
	return &IntegrationAPI_CreateWebhook_Call{Call: _e.mock.On("CreateWebhook", _a0, _a1)}
}

func (_c *IntegrationAPI_CreateWebhook_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_CreateWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_CreateWebhook_Call) Return() *IntegrationAPI_CreateWebhook_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_CreateWebhook_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_CreateWebhook_Call {
	_c.Run(run)
	return _c
}

// DisableConnection provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) DisableConnection(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_DisableConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableConnection'
type IntegrationAPI_DisableConnection_Call struct {
	*mock.Call
}

// DisableConnection is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) DisableConnection(_a0 interface{}, _a1 interface{}) *IntegrationAPI_DisableConnection_Call {
	return &IntegrationAPI_DisableConnection_Call{Call: _e.mock.On("DisableConnection", _a0, _a1)}
}

func (_c *IntegrationAPI_DisableConnection_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_DisableConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_DisableConnection_Call) Return() *IntegrationAPI_DisableConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_DisableConnection_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_DisableConnection_Call {
	_c.Run(run)
	return _c
}

// EnableConnection provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) EnableConnection(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_EnableConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableConnection'
type IntegrationAPI_EnableConnection_Call struct {
	*mock.Call
}

// EnableConnection is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) EnableConnection(_a0 interface{}, _a1 interface{}) *IntegrationAPI_EnableConnection_Call {
	return &IntegrationAPI_EnableConnection_Call{Call: _e.mock.On("EnableConnection", _a0, _a1)}
}

func (_c *IntegrationAPI_EnableConnection_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_EnableConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_EnableConnection_Call) Return() *IntegrationAPI_EnableConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_EnableConnection_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_EnableConnection_Call {
	_c.Run(run)
	return _c
}

// GetConnection provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetConnection(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnection'
type IntegrationAPI_GetConnection_Call struct {
	*mock.Call
}

// GetConnection is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetConnection(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetConnection_Call {
	return &IntegrationAPI_GetConnection_Call{Call: _e.mock.On("GetConnection", _a0, _a1)}
}

func (_c *IntegrationAPI_GetConnection_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetConnection_Call) Return() *IntegrationAPI_GetConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetConnection_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetConnection_Call {
	_c.Run(run)
	return _c
}

// GetProductionAnalysis provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetProductionAnalysis(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetProductionAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionAnalysis'
type IntegrationAPI_GetProductionAnalysis_Call struct {
	*mock.Call
}

// GetProductionAnalysis is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetProductionAnalysis(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetProductionAnalysis_Call {
	return &IntegrationAPI_GetProductionAnalysis_Call{Call: _e.mock.On("GetProductionAnalysis", _a0, _a1)}
}

func (_c *IntegrationAPI_GetProductionAnalysis_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetProductionAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetProductionAnalysis_Call) Return() *IntegrationAPI_GetProductionAnalysis_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetProductionAnalysis_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetProductionAnalysis_Call {
	_c.Run(run)
	return _c
}

// GetProductionCall provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetProductionCall(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetProductionCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionCall'
type IntegrationAPI_GetProductionCall_Call struct {
	*mock.Call
}

// GetProductionCall is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetProductionCall(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetProductionCall_Call {
	return &IntegrationAPI_GetProductionCall_Call{Call: _e.mock.On("GetProductionCall", _a0, _a1)}
}

func (_c *IntegrationAPI_GetProductionCall_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetProductionCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetProductionCall_Call) Return() *IntegrationAPI_GetProductionCall_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetProductionCall_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetProductionCall_Call {
	_c.Run(run)
	return _c
}

// GetProductionCallBySourceRef provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetProductionCallBySourceRef(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetProductionCallBySourceRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionCallBySourceRef'
type IntegrationAPI_GetProductionCallBySourceRef_Call struct {
	*mock.Call
}

// GetProductionCallBySourceRef is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetProductionCallBySourceRef(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetProductionCallBySourceRef_Call {
	return &IntegrationAPI_GetProductionCallBySourceRef_Call{Call: _e.mock.On("GetProductionCallBySourceRef", _a0, _a1)}
}

func (_c *IntegrationAPI_GetProductionCallBySourceRef_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetProductionCallBySourceRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetProductionCallBySourceRef_Call) Return() *IntegrationAPI_GetProductionCallBySourceRef_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetProductionCallBySourceRef_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetProductionCallBySourceRef_Call {
	_c.Run(run)
	return _c
}

// GetProductionIngest provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetProductionIngest(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetProductionIngest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionIngest'
type IntegrationAPI_GetProductionIngest_Call struct {
	*mock.Call
}

// GetProductionIngest is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetProductionIngest(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetProductionIngest_Call {
	return &IntegrationAPI_GetProductionIngest_Call{Call: _e.mock.On("GetProductionIngest", _a0, _a1)}
}

func (_c *IntegrationAPI_GetProductionIngest_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetProductionIngest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetProductionIngest_Call) Return() *IntegrationAPI_GetProductionIngest_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetProductionIngest_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetProductionIngest_Call {
	_c.Run(run)
	return _c
}

// GetProductionTranscription provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetProductionTranscription(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetProductionTranscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionTranscription'
type IntegrationAPI_GetProductionTranscription_Call struct {
	*mock.Call
}

// GetProductionTranscription is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetProductionTranscription(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetProductionTranscription_Call {
	return &IntegrationAPI_GetProductionTranscription_Call{Call: _e.mock.On("GetProductionTranscription", _a0, _a1)}
}

func (_c *IntegrationAPI_GetProductionTranscription_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetProductionTranscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetProductionTranscription_Call) Return() *IntegrationAPI_GetProductionTranscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetProductionTranscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetProductionTranscription_Call {
	_c.Run(run)
	return _c
}

// GetProductionUsage provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetProductionUsage(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetProductionUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductionUsage'
type IntegrationAPI_GetProductionUsage_Call struct {
	*mock.Call
}

// GetProductionUsage is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetProductionUsage(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetProductionUsage_Call {
	return &IntegrationAPI_GetProductionUsage_Call{Call: _e.mock.On("GetProductionUsage", _a0, _a1)}
}

func (_c *IntegrationAPI_GetProductionUsage_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetProductionUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetProductionUsage_Call) Return() *IntegrationAPI_GetProductionUsage_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetProductionUsage_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetProductionUsage_Call {
	_c.Run(run)
	return _c
}

// GetSandboxAnalysis provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetSandboxAnalysis(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetSandboxAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxAnalysis'
type IntegrationAPI_GetSandboxAnalysis_Call struct {
	*mock.Call
}

// GetSandboxAnalysis is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetSandboxAnalysis(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetSandboxAnalysis_Call {
	return &IntegrationAPI_GetSandboxAnalysis_Call{Call: _e.mock.On("GetSandboxAnalysis", _a0, _a1)}
}

func (_c *IntegrationAPI_GetSandboxAnalysis_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetSandboxAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetSandboxAnalysis_Call) Return() *IntegrationAPI_GetSandboxAnalysis_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetSandboxAnalysis_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetSandboxAnalysis_Call {
	_c.Run(run)
	return _c
}

// GetSandboxCall provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetSandboxCall(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetSandboxCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxCall'
type IntegrationAPI_GetSandboxCall_Call struct {
	*mock.Call
}

// GetSandboxCall is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetSandboxCall(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetSandboxCall_Call {
	return &IntegrationAPI_GetSandboxCall_Call{Call: _e.mock.On("GetSandboxCall", _a0, _a1)}
}

func (_c *IntegrationAPI_GetSandboxCall_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetSandboxCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetSandboxCall_Call) Return() *IntegrationAPI_GetSandboxCall_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetSandboxCall_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetSandboxCall_Call {
	_c.Run(run)
	return _c
}

// GetSandboxCallBySourceRef provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetSandboxCallBySourceRef(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetSandboxCallBySourceRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxCallBySourceRef'
type IntegrationAPI_GetSandboxCallBySourceRef_Call struct {
	*mock.Call
}

// GetSandboxCallBySourceRef is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetSandboxCallBySourceRef(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetSandboxCallBySourceRef_Call {
	return &IntegrationAPI_GetSandboxCallBySourceRef_Call{Call: _e.mock.On("GetSandboxCallBySourceRef", _a0, _a1)}
}

func (_c *IntegrationAPI_GetSandboxCallBySourceRef_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetSandboxCallBySourceRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetSandboxCallBySourceRef_Call) Return() *IntegrationAPI_GetSandboxCallBySourceRef_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetSandboxCallBySourceRef_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetSandboxCallBySourceRef_Call {
	_c.Run(run)
	return _c
}

// GetSandboxIngest provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetSandboxIngest(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetSandboxIngest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxIngest'
type IntegrationAPI_GetSandboxIngest_Call struct {
	*mock.Call
}

// GetSandboxIngest is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetSandboxIngest(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetSandboxIngest_Call {
	return &IntegrationAPI_GetSandboxIngest_Call{Call: _e.mock.On("GetSandboxIngest", _a0, _a1)}
}

func (_c *IntegrationAPI_GetSandboxIngest_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetSandboxIngest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetSandboxIngest_Call) Return() *IntegrationAPI_GetSandboxIngest_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetSandboxIngest_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetSandboxIngest_Call {
	_c.Run(run)
	return _c
}

// GetSandboxTranscription provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetSandboxTranscription(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetSandboxTranscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxTranscription'
type IntegrationAPI_GetSandboxTranscription_Call struct {
	*mock.Call
}

// GetSandboxTranscription is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetSandboxTranscription(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetSandboxTranscription_Call {
	return &IntegrationAPI_GetSandboxTranscription_Call{Call: _e.mock.On("GetSandboxTranscription", _a0, _a1)}
}

func (_c *IntegrationAPI_GetSandboxTranscription_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetSandboxTranscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetSandboxTranscription_Call) Return() *IntegrationAPI_GetSandboxTranscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetSandboxTranscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetSandboxTranscription_Call {
	_c.Run(run)
	return _c
}

// GetSandboxUsage provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) GetSandboxUsage(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_GetSandboxUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxUsage'
type IntegrationAPI_GetSandboxUsage_Call struct {
	*mock.Call
}

// GetSandboxUsage is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) GetSandboxUsage(_a0 interface{}, _a1 interface{}) *IntegrationAPI_GetSandboxUsage_Call {
	return &IntegrationAPI_GetSandboxUsage_Call{Call: _e.mock.On("GetSandboxUsage", _a0, _a1)}
}

func (_c *IntegrationAPI_GetSandboxUsage_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_GetSandboxUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_GetSandboxUsage_Call) Return() *IntegrationAPI_GetSandboxUsage_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_GetSandboxUsage_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_GetSandboxUsage_Call {
	_c.Run(run)
	return _c
}

// IngestProduction provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) IngestProduction(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_IngestProduction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestProduction'
type IntegrationAPI_IngestProduction_Call struct {
	*mock.Call
}

// IngestProduction is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) IngestProduction(_a0 interface{}, _a1 interface{}) *IntegrationAPI_IngestProduction_Call {
	return &IntegrationAPI_IngestProduction_Call{Call: _e.mock.On("IngestProduction", _a0, _a1)}
}

func (_c *IntegrationAPI_IngestProduction_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_IngestProduction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_IngestProduction_Call) Return() *IntegrationAPI_IngestProduction_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_IngestProduction_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_IngestProduction_Call {
	_c.Run(run)
	return _c
}

// IngestSandbox provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) IngestSandbox(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_IngestSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestSandbox'
type IntegrationAPI_IngestSandbox_Call struct {
	*mock.Call
}

// IngestSandbox is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) IngestSandbox(_a0 interface{}, _a1 interface{}) *IntegrationAPI_IngestSandbox_Call {
	return &IntegrationAPI_IngestSandbox_Call{Call: _e.mock.On("IngestSandbox", _a0, _a1)}
}

func (_c *IntegrationAPI_IngestSandbox_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_IngestSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_IngestSandbox_Call) Return() *IntegrationAPI_IngestSandbox_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_IngestSandbox_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_IngestSandbox_Call {
	_c.Run(run)
	return _c
}

// ListAuditEvents provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListAuditEvents(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditEvents'
type IntegrationAPI_ListAuditEvents_Call struct {
	*mock.Call
}

// ListAuditEvents is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListAuditEvents(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListAuditEvents_Call {
	return &IntegrationAPI_ListAuditEvents_Call{Call: _e.mock.On("ListAuditEvents", _a0, _a1)}
}

func (_c *IntegrationAPI_ListAuditEvents_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListAuditEvents_Call) Return() *IntegrationAPI_ListAuditEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListAuditEvents_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListAuditEvents_Call {
	_c.Run(run)
	return _c
}

// ListConnections provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListConnections(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConnections'
type IntegrationAPI_ListConnections_Call struct {
	*mock.Call
}

// ListConnections is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListConnections(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListConnections_Call {
	return &IntegrationAPI_ListConnections_Call{Call: _e.mock.On("ListConnections", _a0, _a1)}
}

func (_c *IntegrationAPI_ListConnections_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListConnections_Call) Return() *IntegrationAPI_ListConnections_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListConnections_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListConnections_Call {
	_c.Run(run)
	return _c
}

// ListIngestItems provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListIngestItems(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListIngestItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIngestItems'
type IntegrationAPI_ListIngestItems_Call struct {
	*mock.Call
}

// ListIngestItems is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListIngestItems(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListIngestItems_Call {
	return &IntegrationAPI_ListIngestItems_Call{Call: _e.mock.On("ListIngestItems", _a0, _a1)}
}

func (_c *IntegrationAPI_ListIngestItems_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListIngestItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListIngestItems_Call) Return() *IntegrationAPI_ListIngestItems_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListIngestItems_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListIngestItems_Call {
	_c.Run(run)
	return _c
}

// ListProductionCalls provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListProductionCalls(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListProductionCalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductionCalls'
type IntegrationAPI_ListProductionCalls_Call struct {
	*mock.Call
}

// ListProductionCalls is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListProductionCalls(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListProductionCalls_Call {
	return &IntegrationAPI_ListProductionCalls_Call{Call: _e.mock.On("ListProductionCalls", _a0, _a1)}
}

func (_c *IntegrationAPI_ListProductionCalls_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListProductionCalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListProductionCalls_Call) Return() *IntegrationAPI_ListProductionCalls_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListProductionCalls_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListProductionCalls_Call {
	_c.Run(run)
	return _c
}

// ListProductionDestinations provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListProductionDestinations(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListProductionDestinations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductionDestinations'
type IntegrationAPI_ListProductionDestinations_Call struct {
	*mock.Call
}

// ListProductionDestinations is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListProductionDestinations(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListProductionDestinations_Call {
	return &IntegrationAPI_ListProductionDestinations_Call{Call: _e.mock.On("ListProductionDestinations", _a0, _a1)}
}

func (_c *IntegrationAPI_ListProductionDestinations_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListProductionDestinations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListProductionDestinations_Call) Return() *IntegrationAPI_ListProductionDestinations_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListProductionDestinations_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListProductionDestinations_Call {
	_c.Run(run)
	return _c
}

// ListProductionFolders provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListProductionFolders(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListProductionFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProductionFolders'
type IntegrationAPI_ListProductionFolders_Call struct {
	*mock.Call
}

// ListProductionFolders is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListProductionFolders(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListProductionFolders_Call {
	return &IntegrationAPI_ListProductionFolders_Call{Call: _e.mock.On("ListProductionFolders", _a0, _a1)}
}

func (_c *IntegrationAPI_ListProductionFolders_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListProductionFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListProductionFolders_Call) Return() *IntegrationAPI_ListProductionFolders_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListProductionFolders_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListProductionFolders_Call {
	_c.Run(run)
	return _c
}

// ListSandboxCalls provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListSandboxCalls(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListSandboxCalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxCalls'
type IntegrationAPI_ListSandboxCalls_Call struct {
	*mock.Call
}

// ListSandboxCalls is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListSandboxCalls(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListSandboxCalls_Call {
	return &IntegrationAPI_ListSandboxCalls_Call{Call: _e.mock.On("ListSandboxCalls", _a0, _a1)}
}

func (_c *IntegrationAPI_ListSandboxCalls_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListSandboxCalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListSandboxCalls_Call) Return() *IntegrationAPI_ListSandboxCalls_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListSandboxCalls_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListSandboxCalls_Call {
	_c.Run(run)
	return _c
}

// ListSandboxDestinations provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListSandboxDestinations(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListSandboxDestinations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxDestinations'
type IntegrationAPI_ListSandboxDestinations_Call struct {
	*mock.Call
}

// ListSandboxDestinations is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListSandboxDestinations(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListSandboxDestinations_Call {
	return &IntegrationAPI_ListSandboxDestinations_Call{Call: _e.mock.On("ListSandboxDestinations", _a0, _a1)}
}

func (_c *IntegrationAPI_ListSandboxDestinations_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListSandboxDestinations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListSandboxDestinations_Call) Return() *IntegrationAPI_ListSandboxDestinations_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListSandboxDestinations_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListSandboxDestinations_Call {
	_c.Run(run)
	return _c
}

// ListSandboxFolders provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListSandboxFolders(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListSandboxFolders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSandboxFolders'
type IntegrationAPI_ListSandboxFolders_Call struct {
	*mock.Call
}

// ListSandboxFolders is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListSandboxFolders(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListSandboxFolders_Call {
	return &IntegrationAPI_ListSandboxFolders_Call{Call: _e.mock.On("ListSandboxFolders", _a0, _a1)}
}

func (_c *IntegrationAPI_ListSandboxFolders_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListSandboxFolders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListSandboxFolders_Call) Return() *IntegrationAPI_ListSandboxFolders_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListSandboxFolders_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListSandboxFolders_Call {
	_c.Run(run)
	return _c
}

// ListWebhookDeliveries provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListWebhookDeliveries(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListWebhookDeliveries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWebhookDeliveries'
type IntegrationAPI_ListWebhookDeliveries_Call struct {
	*mock.Call
}

// ListWebhookDeliveries is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListWebhookDeliveries(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListWebhookDeliveries_Call {
	return &IntegrationAPI_ListWebhookDeliveries_Call{Call: _e.mock.On("ListWebhookDeliveries", _a0, _a1)}
}

func (_c *IntegrationAPI_ListWebhookDeliveries_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListWebhookDeliveries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListWebhookDeliveries_Call) Return() *IntegrationAPI_ListWebhookDeliveries_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListWebhookDeliveries_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListWebhookDeliveries_Call {
	_c.Run(run)
	return _c
}

// ListWebhooks provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ListWebhooks(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ListWebhooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWebhooks'
type IntegrationAPI_ListWebhooks_Call struct {
	*mock.Call
}

// ListWebhooks is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ListWebhooks(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ListWebhooks_Call {
	return &IntegrationAPI_ListWebhooks_Call{Call: _e.mock.On("ListWebhooks", _a0, _a1)}
}

func (_c *IntegrationAPI_ListWebhooks_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ListWebhooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ListWebhooks_Call) Return() *IntegrationAPI_ListWebhooks_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ListWebhooks_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ListWebhooks_Call {
	_c.Run(run)
	return _c
}

// ReplayWebhookDelivery provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) ReplayWebhookDelivery(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_ReplayWebhookDelivery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplayWebhookDelivery'
type IntegrationAPI_ReplayWebhookDelivery_Call struct {
	*mock.Call
}

// ReplayWebhookDelivery is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) ReplayWebhookDelivery(_a0 interface{}, _a1 interface{}) *IntegrationAPI_ReplayWebhookDelivery_Call {
	return &IntegrationAPI_ReplayWebhookDelivery_Call{Call: _e.mock.On("ReplayWebhookDelivery", _a0, _a1)}
}

func (_c *IntegrationAPI_ReplayWebhookDelivery_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_ReplayWebhookDelivery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_ReplayWebhookDelivery_Call) Return() *IntegrationAPI_ReplayWebhookDelivery_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_ReplayWebhookDelivery_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_ReplayWebhookDelivery_Call {
	_c.Run(run)
	return _c
}

// RetryIngestItem provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) RetryIngestItem(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_RetryIngestItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryIngestItem'
type IntegrationAPI_RetryIngestItem_Call struct {
	*mock.Call
}

// RetryIngestItem is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) RetryIngestItem(_a0 interface{}, _a1 interface{}) *IntegrationAPI_RetryIngestItem_Call {
	return &IntegrationAPI_RetryIngestItem_Call{Call: _e.mock.On("RetryIngestItem", _a0, _a1)}
}

func (_c *IntegrationAPI_RetryIngestItem_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_RetryIngestItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_RetryIngestItem_Call) Return() *IntegrationAPI_RetryIngestItem_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_RetryIngestItem_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_RetryIngestItem_Call {
	_c.Run(run)
	return _c
}

// RevokeConnection provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) RevokeConnection(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_RevokeConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeConnection'
type IntegrationAPI_RevokeConnection_Call struct {
	*mock.Call
}

// RevokeConnection is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) RevokeConnection(_a0 interface{}, _a1 interface{}) *IntegrationAPI_RevokeConnection_Call {
	return &IntegrationAPI_RevokeConnection_Call{Call: _e.mock.On("RevokeConnection", _a0, _a1)}
}

func (_c *IntegrationAPI_RevokeConnection_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_RevokeConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_RevokeConnection_Call) Return() *IntegrationAPI_RevokeConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_RevokeConnection_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_RevokeConnection_Call {
	_c.Run(run)
	return _c
}

// RevokeWebhook provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) RevokeWebhook(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_RevokeWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeWebhook'
type IntegrationAPI_RevokeWebhook_Call struct {
	*mock.Call
}

// RevokeWebhook is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) RevokeWebhook(_a0 interface{}, _a1 interface{}) *IntegrationAPI_RevokeWebhook_Call {
	return &IntegrationAPI_RevokeWebhook_Call{Call: _e.mock.On("RevokeWebhook", _a0, _a1)}
}

func (_c *IntegrationAPI_RevokeWebhook_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_RevokeWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_RevokeWebhook_Call) Return() *IntegrationAPI_RevokeWebhook_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_RevokeWebhook_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_RevokeWebhook_Call {
	_c.Run(run)
	return _c
}

// TestWebhook provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) TestWebhook(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_TestWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestWebhook'
type IntegrationAPI_TestWebhook_Call struct {
	*mock.Call
}

// TestWebhook is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) TestWebhook(_a0 interface{}, _a1 interface{}) *IntegrationAPI_TestWebhook_Call {
	return &IntegrationAPI_TestWebhook_Call{Call: _e.mock.On("TestWebhook", _a0, _a1)}
}

func (_c *IntegrationAPI_TestWebhook_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_TestWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_TestWebhook_Call) Return() *IntegrationAPI_TestWebhook_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_TestWebhook_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_TestWebhook_Call {
	_c.Run(run)
	return _c
}

// UpdateConnection provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) UpdateConnection(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_UpdateConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnection'
type IntegrationAPI_UpdateConnection_Call struct {
	*mock.Call
}

// UpdateConnection is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) UpdateConnection(_a0 interface{}, _a1 interface{}) *IntegrationAPI_UpdateConnection_Call {
	return &IntegrationAPI_UpdateConnection_Call{Call: _e.mock.On("UpdateConnection", _a0, _a1)}
}

func (_c *IntegrationAPI_UpdateConnection_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_UpdateConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_UpdateConnection_Call) Return() *IntegrationAPI_UpdateConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_UpdateConnection_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_UpdateConnection_Call {
	_c.Run(run)
	return _c
}

// UploadProduction provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) UploadProduction(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_UploadProduction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadProduction'
type IntegrationAPI_UploadProduction_Call struct {
	*mock.Call
}

// UploadProduction is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) UploadProduction(_a0 interface{}, _a1 interface{}) *IntegrationAPI_UploadProduction_Call {
	return &IntegrationAPI_UploadProduction_Call{Call: _e.mock.On("UploadProduction", _a0, _a1)}
}

func (_c *IntegrationAPI_UploadProduction_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_UploadProduction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_UploadProduction_Call) Return() *IntegrationAPI_UploadProduction_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_UploadProduction_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_UploadProduction_Call {
	_c.Run(run)
	return _c
}

// UploadSandbox provides a mock function with given fields: _a0, _a1
func (_m *IntegrationAPI) UploadSandbox(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// IntegrationAPI_UploadSandbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadSandbox'
type IntegrationAPI_UploadSandbox_Call struct {
	*mock.Call
}

// UploadSandbox is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *IntegrationAPI_Expecter) UploadSandbox(_a0 interface{}, _a1 interface{}) *IntegrationAPI_UploadSandbox_Call {
	return &IntegrationAPI_UploadSandbox_Call{Call: _e.mock.On("UploadSandbox", _a0, _a1)}
}

func (_c *IntegrationAPI_UploadSandbox_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *IntegrationAPI_UploadSandbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *IntegrationAPI_UploadSandbox_Call) Return() *IntegrationAPI_UploadSandbox_Call {
	_c.Call.Return()
	return _c
}

func (_c *IntegrationAPI_UploadSandbox_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *IntegrationAPI_UploadSandbox_Call {
	_c.Run(run)
	return _c
}

// NewIntegrationAPI creates a new instance of IntegrationAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationAPI {
	mock := &IntegrationAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
