// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// QualityReviewAPI is an autogenerated mock type for the QualityReviewAPI type
type QualityReviewAPI struct {
	mock.Mock
}

type QualityReviewAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *QualityReviewAPI) EXPECT() *QualityReviewAPI_Expecter {
	return &QualityReviewAPI_Expecter{mock: &_m.Mock}
}

// ChallengeAnalysis provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) ChallengeAnalysis(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_ChallengeAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChallengeAnalysis'
type QualityReviewAPI_ChallengeAnalysis_Call struct {
	*mock.Call
}

// ChallengeAnalysis is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) ChallengeAnalysis(w interface{}, r interface{}) *QualityReviewAPI_ChallengeAnalysis_Call {
	return &QualityReviewAPI_ChallengeAnalysis_Call{Call: _e.mock.On("ChallengeAnalysis", w, r)}
}

func (_c *QualityReviewAPI_ChallengeAnalysis_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_ChallengeAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_ChallengeAnalysis_Call) Return() *QualityReviewAPI_ChallengeAnalysis_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_ChallengeAnalysis_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_ChallengeAnalysis_Call {
	_c.Run(run)
	return _c
}

// Claim provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) Claim(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type QualityReviewAPI_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) Claim(w interface{}, r interface{}) *QualityReviewAPI_Claim_Call {
	return &QualityReviewAPI_Claim_Call{Call: _e.mock.On("Claim", w, r)}
}

func (_c *QualityReviewAPI_Claim_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_Claim_Call) Return() *QualityReviewAPI_Claim_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_Claim_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_Claim_Call {
	_c.Run(run)
	return _c
}

// Create provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type QualityReviewAPI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) Create(w interface{}, r interface{}) *QualityReviewAPI_Create_Call {
	return &QualityReviewAPI_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *QualityReviewAPI_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_Create_Call) Return() *QualityReviewAPI_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_Create_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_Create_Call {
	_c.Run(run)
	return _c
}

// CreateAnalysisComment provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) CreateAnalysisComment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_CreateAnalysisComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAnalysisComment'
type QualityReviewAPI_CreateAnalysisComment_Call struct {
	*mock.Call
}

// CreateAnalysisComment is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) CreateAnalysisComment(w interface{}, r interface{}) *QualityReviewAPI_CreateAnalysisComment_Call {
	return &QualityReviewAPI_CreateAnalysisComment_Call{Call: _e.mock.On("CreateAnalysisComment", w, r)}
}

func (_c *QualityReviewAPI_CreateAnalysisComment_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_CreateAnalysisComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_CreateAnalysisComment_Call) Return() *QualityReviewAPI_CreateAnalysisComment_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_CreateAnalysisComment_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_CreateAnalysisComment_Call {
	_c.Run(run)
	return _c
}

// CreateAppeal provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) CreateAppeal(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_CreateAppeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppeal'
type QualityReviewAPI_CreateAppeal_Call struct {
	*mock.Call
}

// CreateAppeal is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) CreateAppeal(w interface{}, r interface{}) *QualityReviewAPI_CreateAppeal_Call {
	return &QualityReviewAPI_CreateAppeal_Call{Call: _e.mock.On("CreateAppeal", w, r)}
}

func (_c *QualityReviewAPI_CreateAppeal_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_CreateAppeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_CreateAppeal_Call) Return() *QualityReviewAPI_CreateAppeal_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_CreateAppeal_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_CreateAppeal_Call {
	_c.Run(run)
	return _c
}

// DiscardDraft provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) DiscardDraft(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_DiscardDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscardDraft'
type QualityReviewAPI_DiscardDraft_Call struct {
	*mock.Call
}

// DiscardDraft is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) DiscardDraft(w interface{}, r interface{}) *QualityReviewAPI_DiscardDraft_Call {
	return &QualityReviewAPI_DiscardDraft_Call{Call: _e.mock.On("DiscardDraft", w, r)}
}

func (_c *QualityReviewAPI_DiscardDraft_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_DiscardDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_DiscardDraft_Call) Return() *QualityReviewAPI_DiscardDraft_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_DiscardDraft_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_DiscardDraft_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) Get(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type QualityReviewAPI_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) Get(w interface{}, r interface{}) *QualityReviewAPI_Get_Call {
	return &QualityReviewAPI_Get_Call{Call: _e.mock.On("Get", w, r)}
}

func (_c *QualityReviewAPI_Get_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_Get_Call) Return() *QualityReviewAPI_Get_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_Get_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_Get_Call {
	_c.Run(run)
	return _c
}

// GetAnalysisContext provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) GetAnalysisContext(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_GetAnalysisContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalysisContext'
type QualityReviewAPI_GetAnalysisContext_Call struct {
	*mock.Call
}

// GetAnalysisContext is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) GetAnalysisContext(w interface{}, r interface{}) *QualityReviewAPI_GetAnalysisContext_Call {
	return &QualityReviewAPI_GetAnalysisContext_Call{Call: _e.mock.On("GetAnalysisContext", w, r)}
}

func (_c *QualityReviewAPI_GetAnalysisContext_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_GetAnalysisContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_GetAnalysisContext_Call) Return() *QualityReviewAPI_GetAnalysisContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_GetAnalysisContext_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_GetAnalysisContext_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) List(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type QualityReviewAPI_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) List(w interface{}, r interface{}) *QualityReviewAPI_List_Call {
	return &QualityReviewAPI_List_Call{Call: _e.mock.On("List", w, r)}
}

func (_c *QualityReviewAPI_List_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_List_Call) Return() *QualityReviewAPI_List_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_List_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_List_Call {
	_c.Run(run)
	return _c
}

// ListEvents provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) ListEvents(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type QualityReviewAPI_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) ListEvents(w interface{}, r interface{}) *QualityReviewAPI_ListEvents_Call {
	return &QualityReviewAPI_ListEvents_Call{Call: _e.mock.On("ListEvents", w, r)}
}

func (_c *QualityReviewAPI_ListEvents_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_ListEvents_Call) Return() *QualityReviewAPI_ListEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_ListEvents_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_ListEvents_Call {
	_c.Run(run)
	return _c
}

// Publish provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) Publish(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type QualityReviewAPI_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) Publish(w interface{}, r interface{}) *QualityReviewAPI_Publish_Call {
	return &QualityReviewAPI_Publish_Call{Call: _e.mock.On("Publish", w, r)}
}

func (_c *QualityReviewAPI_Publish_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_Publish_Call) Return() *QualityReviewAPI_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_Publish_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_Publish_Call {
	_c.Run(run)
	return _c
}

// ResolveAppeal provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) ResolveAppeal(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_ResolveAppeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAppeal'
type QualityReviewAPI_ResolveAppeal_Call struct {
	*mock.Call
}

// ResolveAppeal is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) ResolveAppeal(w interface{}, r interface{}) *QualityReviewAPI_ResolveAppeal_Call {
	return &QualityReviewAPI_ResolveAppeal_Call{Call: _e.mock.On("ResolveAppeal", w, r)}
}

func (_c *QualityReviewAPI_ResolveAppeal_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_ResolveAppeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_ResolveAppeal_Call) Return() *QualityReviewAPI_ResolveAppeal_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_ResolveAppeal_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_ResolveAppeal_Call {
	_c.Run(run)
	return _c
}

// SaveDraft provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) SaveDraft(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_SaveDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDraft'
type QualityReviewAPI_SaveDraft_Call struct {
	*mock.Call
}

// SaveDraft is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) SaveDraft(w interface{}, r interface{}) *QualityReviewAPI_SaveDraft_Call {
	return &QualityReviewAPI_SaveDraft_Call{Call: _e.mock.On("SaveDraft", w, r)}
}

func (_c *QualityReviewAPI_SaveDraft_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_SaveDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_SaveDraft_Call) Return() *QualityReviewAPI_SaveDraft_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_SaveDraft_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_SaveDraft_Call {
	_c.Run(run)
	return _c
}

// UpdateAnalysisComment provides a mock function with given fields: w, r
func (_m *QualityReviewAPI) UpdateAnalysisComment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// QualityReviewAPI_UpdateAnalysisComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAnalysisComment'
type QualityReviewAPI_UpdateAnalysisComment_Call struct {
	*mock.Call
}

// UpdateAnalysisComment is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *QualityReviewAPI_Expecter) UpdateAnalysisComment(w interface{}, r interface{}) *QualityReviewAPI_UpdateAnalysisComment_Call {
	return &QualityReviewAPI_UpdateAnalysisComment_Call{Call: _e.mock.On("UpdateAnalysisComment", w, r)}
}

func (_c *QualityReviewAPI_UpdateAnalysisComment_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *QualityReviewAPI_UpdateAnalysisComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *QualityReviewAPI_UpdateAnalysisComment_Call) Return() *QualityReviewAPI_UpdateAnalysisComment_Call {
	_c.Call.Return()
	return _c
}

func (_c *QualityReviewAPI_UpdateAnalysisComment_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *QualityReviewAPI_UpdateAnalysisComment_Call {
	_c.Run(run)
	return _c
}

// NewQualityReviewAPI creates a new instance of QualityReviewAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQualityReviewAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *QualityReviewAPI {
	mock := &QualityReviewAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
