// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AnalysisAPI is an autogenerated mock type for the AnalysisAPI type
type AnalysisAPI struct {
	mock.Mock
}

type AnalysisAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalysisAPI) EXPECT() *AnalysisAPI_Expecter {
	return &AnalysisAPI_Expecter{mock: &_m.Mock}
}

// AnalyzeCall provides a mock function with given fields: w, r
func (_m *AnalysisAPI) AnalyzeCall(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalysisAPI_AnalyzeCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeCall'
type AnalysisAPI_AnalyzeCall_Call struct {
	*mock.Call
}

// AnalyzeCall is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalysisAPI_Expecter) AnalyzeCall(w interface{}, r interface{}) *AnalysisAPI_AnalyzeCall_Call {
	return &AnalysisAPI_AnalyzeCall_Call{Call: _e.mock.On("AnalyzeCall", w, r)}
}

func (_c *AnalysisAPI_AnalyzeCall_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalysisAPI_AnalyzeCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalysisAPI_AnalyzeCall_Call) Return() *AnalysisAPI_AnalyzeCall_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalysisAPI_AnalyzeCall_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalysisAPI_AnalyzeCall_Call {
	_c.Run(run)
	return _c
}

// GetByCallUUID provides a mock function with given fields: w, r
func (_m *AnalysisAPI) GetByCallUUID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalysisAPI_GetByCallUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCallUUID'
type AnalysisAPI_GetByCallUUID_Call struct {
	*mock.Call
}

// GetByCallUUID is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalysisAPI_Expecter) GetByCallUUID(w interface{}, r interface{}) *AnalysisAPI_GetByCallUUID_Call {
	return &AnalysisAPI_GetByCallUUID_Call{Call: _e.mock.On("GetByCallUUID", w, r)}
}

func (_c *AnalysisAPI_GetByCallUUID_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalysisAPI_GetByCallUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalysisAPI_GetByCallUUID_Call) Return() *AnalysisAPI_GetByCallUUID_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalysisAPI_GetByCallUUID_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalysisAPI_GetByCallUUID_Call {
	_c.Run(run)
	return _c
}

func (_m *AnalysisAPI) ListAppliedInstructions(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
func (_m *AnalysisAPI) GetAppliedInstruction(w http.ResponseWriter, r *http.Request) { _m.Called(w, r) }

// NewAnalysisAPI creates a new instance of AnalysisAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalysisAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalysisAPI {
	mock := &AnalysisAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
