// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AdminAPI is an autogenerated mock type for the AdminAPI type
type AdminAPI struct {
	mock.Mock
}

type AdminAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminAPI) EXPECT() *AdminAPI_Expecter {
	return &AdminAPI_Expecter{mock: &_m.Mock}
}

// CancelCompanySubscription provides a mock function with given fields: w, r
func (_m *AdminAPI) CancelCompanySubscription(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_CancelCompanySubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelCompanySubscription'
type AdminAPI_CancelCompanySubscription_Call struct {
	*mock.Call
}

// CancelCompanySubscription is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) CancelCompanySubscription(w interface{}, r interface{}) *AdminAPI_CancelCompanySubscription_Call {
	return &AdminAPI_CancelCompanySubscription_Call{Call: _e.mock.On("CancelCompanySubscription", w, r)}
}

func (_c *AdminAPI_CancelCompanySubscription_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_CancelCompanySubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_CancelCompanySubscription_Call) Return() *AdminAPI_CancelCompanySubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_CancelCompanySubscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_CancelCompanySubscription_Call {
	_c.Run(run)
	return _c
}

// CancelPersonalSubscription provides a mock function with given fields: w, r
func (_m *AdminAPI) CancelPersonalSubscription(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_CancelPersonalSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPersonalSubscription'
type AdminAPI_CancelPersonalSubscription_Call struct {
	*mock.Call
}

// CancelPersonalSubscription is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) CancelPersonalSubscription(w interface{}, r interface{}) *AdminAPI_CancelPersonalSubscription_Call {
	return &AdminAPI_CancelPersonalSubscription_Call{Call: _e.mock.On("CancelPersonalSubscription", w, r)}
}

func (_c *AdminAPI_CancelPersonalSubscription_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_CancelPersonalSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_CancelPersonalSubscription_Call) Return() *AdminAPI_CancelPersonalSubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_CancelPersonalSubscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_CancelPersonalSubscription_Call {
	_c.Run(run)
	return _c
}

// ChangeUserRole provides a mock function with given fields: w, r
func (_m *AdminAPI) ChangeUserRole(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_ChangeUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeUserRole'
type AdminAPI_ChangeUserRole_Call struct {
	*mock.Call
}

// ChangeUserRole is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) ChangeUserRole(w interface{}, r interface{}) *AdminAPI_ChangeUserRole_Call {
	return &AdminAPI_ChangeUserRole_Call{Call: _e.mock.On("ChangeUserRole", w, r)}
}

func (_c *AdminAPI_ChangeUserRole_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_ChangeUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_ChangeUserRole_Call) Return() *AdminAPI_ChangeUserRole_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_ChangeUserRole_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_ChangeUserRole_Call {
	_c.Run(run)
	return _c
}

// GetCall provides a mock function with given fields: w, r
func (_m *AdminAPI) GetCall(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCall'
type AdminAPI_GetCall_Call struct {
	*mock.Call
}

// GetCall is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetCall(w interface{}, r interface{}) *AdminAPI_GetCall_Call {
	return &AdminAPI_GetCall_Call{Call: _e.mock.On("GetCall", w, r)}
}

func (_c *AdminAPI_GetCall_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetCall_Call) Return() *AdminAPI_GetCall_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetCall_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetCall_Call {
	_c.Run(run)
	return _c
}

// GetCallAudio provides a mock function with given fields: w, r
func (_m *AdminAPI) GetCallAudio(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetCallAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCallAudio'
type AdminAPI_GetCallAudio_Call struct {
	*mock.Call
}

// GetCallAudio is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetCallAudio(w interface{}, r interface{}) *AdminAPI_GetCallAudio_Call {
	return &AdminAPI_GetCallAudio_Call{Call: _e.mock.On("GetCallAudio", w, r)}
}

func (_c *AdminAPI_GetCallAudio_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetCallAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetCallAudio_Call) Return() *AdminAPI_GetCallAudio_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetCallAudio_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetCallAudio_Call {
	_c.Run(run)
	return _c
}

// GetCapabilities provides a mock function with given fields: w, r
func (_m *AdminAPI) GetCapabilities(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type AdminAPI_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetCapabilities(w interface{}, r interface{}) *AdminAPI_GetCapabilities_Call {
	return &AdminAPI_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities", w, r)}
}

func (_c *AdminAPI_GetCapabilities_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetCapabilities_Call) Return() *AdminAPI_GetCapabilities_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetCapabilities_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetCapabilities_Call {
	_c.Run(run)
	return _c
}

// GetCompany provides a mock function with given fields: w, r
func (_m *AdminAPI) GetCompany(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompany'
type AdminAPI_GetCompany_Call struct {
	*mock.Call
}

// GetCompany is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetCompany(w interface{}, r interface{}) *AdminAPI_GetCompany_Call {
	return &AdminAPI_GetCompany_Call{Call: _e.mock.On("GetCompany", w, r)}
}

func (_c *AdminAPI_GetCompany_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetCompany_Call) Return() *AdminAPI_GetCompany_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetCompany_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetCompany_Call {
	_c.Run(run)
	return _c
}

// GetCompanySubscription provides a mock function with given fields: w, r
func (_m *AdminAPI) GetCompanySubscription(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetCompanySubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanySubscription'
type AdminAPI_GetCompanySubscription_Call struct {
	*mock.Call
}

// GetCompanySubscription is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetCompanySubscription(w interface{}, r interface{}) *AdminAPI_GetCompanySubscription_Call {
	return &AdminAPI_GetCompanySubscription_Call{Call: _e.mock.On("GetCompanySubscription", w, r)}
}

func (_c *AdminAPI_GetCompanySubscription_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetCompanySubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetCompanySubscription_Call) Return() *AdminAPI_GetCompanySubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetCompanySubscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetCompanySubscription_Call {
	_c.Run(run)
	return _c
}

// GetPersonalSubscription provides a mock function with given fields: w, r
func (_m *AdminAPI) GetPersonalSubscription(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetPersonalSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalSubscription'
type AdminAPI_GetPersonalSubscription_Call struct {
	*mock.Call
}

// GetPersonalSubscription is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetPersonalSubscription(w interface{}, r interface{}) *AdminAPI_GetPersonalSubscription_Call {
	return &AdminAPI_GetPersonalSubscription_Call{Call: _e.mock.On("GetPersonalSubscription", w, r)}
}

func (_c *AdminAPI_GetPersonalSubscription_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetPersonalSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetPersonalSubscription_Call) Return() *AdminAPI_GetPersonalSubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetPersonalSubscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetPersonalSubscription_Call {
	_c.Run(run)
	return _c
}

// GetUser provides a mock function with given fields: w, r
func (_m *AdminAPI) GetUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type AdminAPI_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetUser(w interface{}, r interface{}) *AdminAPI_GetUser_Call {
	return &AdminAPI_GetUser_Call{Call: _e.mock.On("GetUser", w, r)}
}

func (_c *AdminAPI_GetUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetUser_Call) Return() *AdminAPI_GetUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetUser_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetUser_Call {
	_c.Run(run)
	return _c
}

// GrantCompanySubscription provides a mock function with given fields: w, r
func (_m *AdminAPI) GrantCompanySubscription(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GrantCompanySubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantCompanySubscription'
type AdminAPI_GrantCompanySubscription_Call struct {
	*mock.Call
}

// GrantCompanySubscription is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GrantCompanySubscription(w interface{}, r interface{}) *AdminAPI_GrantCompanySubscription_Call {
	return &AdminAPI_GrantCompanySubscription_Call{Call: _e.mock.On("GrantCompanySubscription", w, r)}
}

func (_c *AdminAPI_GrantCompanySubscription_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GrantCompanySubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GrantCompanySubscription_Call) Return() *AdminAPI_GrantCompanySubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GrantCompanySubscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GrantCompanySubscription_Call {
	_c.Run(run)
	return _c
}

// GrantPersonalSubscription provides a mock function with given fields: w, r
func (_m *AdminAPI) GrantPersonalSubscription(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GrantPersonalSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantPersonalSubscription'
type AdminAPI_GrantPersonalSubscription_Call struct {
	*mock.Call
}

// GrantPersonalSubscription is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GrantPersonalSubscription(w interface{}, r interface{}) *AdminAPI_GrantPersonalSubscription_Call {
	return &AdminAPI_GrantPersonalSubscription_Call{Call: _e.mock.On("GrantPersonalSubscription", w, r)}
}

func (_c *AdminAPI_GrantPersonalSubscription_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GrantPersonalSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GrantPersonalSubscription_Call) Return() *AdminAPI_GrantPersonalSubscription_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GrantPersonalSubscription_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GrantPersonalSubscription_Call {
	_c.Run(run)
	return _c
}

// ListCompanies provides a mock function with given fields: w, r
func (_m *AdminAPI) ListCompanies(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_ListCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompanies'
type AdminAPI_ListCompanies_Call struct {
	*mock.Call
}

// ListCompanies is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) ListCompanies(w interface{}, r interface{}) *AdminAPI_ListCompanies_Call {
	return &AdminAPI_ListCompanies_Call{Call: _e.mock.On("ListCompanies", w, r)}
}

func (_c *AdminAPI_ListCompanies_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_ListCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_ListCompanies_Call) Return() *AdminAPI_ListCompanies_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_ListCompanies_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_ListCompanies_Call {
	_c.Run(run)
	return _c
}

// ListUserCalls provides a mock function with given fields: w, r
func (_m *AdminAPI) ListUserCalls(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_ListUserCalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserCalls'
type AdminAPI_ListUserCalls_Call struct {
	*mock.Call
}

// ListUserCalls is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) ListUserCalls(w interface{}, r interface{}) *AdminAPI_ListUserCalls_Call {
	return &AdminAPI_ListUserCalls_Call{Call: _e.mock.On("ListUserCalls", w, r)}
}

func (_c *AdminAPI_ListUserCalls_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_ListUserCalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_ListUserCalls_Call) Return() *AdminAPI_ListUserCalls_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_ListUserCalls_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_ListUserCalls_Call {
	_c.Run(run)
	return _c
}

// ListUserSessions provides a mock function with given fields: w, r
func (_m *AdminAPI) ListUserSessions(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_ListUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserSessions'
type AdminAPI_ListUserSessions_Call struct {
	*mock.Call
}

// ListUserSessions is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) ListUserSessions(w interface{}, r interface{}) *AdminAPI_ListUserSessions_Call {
	return &AdminAPI_ListUserSessions_Call{Call: _e.mock.On("ListUserSessions", w, r)}
}

func (_c *AdminAPI_ListUserSessions_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_ListUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_ListUserSessions_Call) Return() *AdminAPI_ListUserSessions_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_ListUserSessions_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_ListUserSessions_Call {
	_c.Run(run)
	return _c
}

// ListUsers provides a mock function with given fields: w, r
func (_m *AdminAPI) ListUsers(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type AdminAPI_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) ListUsers(w interface{}, r interface{}) *AdminAPI_ListUsers_Call {
	return &AdminAPI_ListUsers_Call{Call: _e.mock.On("ListUsers", w, r)}
}

func (_c *AdminAPI_ListUsers_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_ListUsers_Call) Return() *AdminAPI_ListUsers_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_ListUsers_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_ListUsers_Call {
	_c.Run(run)
	return _c
}

// ResetCompanyUsage provides a mock function with given fields: w, r
func (_m *AdminAPI) ResetCompanyUsage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_ResetCompanyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetCompanyUsage'
type AdminAPI_ResetCompanyUsage_Call struct {
	*mock.Call
}

// ResetCompanyUsage is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) ResetCompanyUsage(w interface{}, r interface{}) *AdminAPI_ResetCompanyUsage_Call {
	return &AdminAPI_ResetCompanyUsage_Call{Call: _e.mock.On("ResetCompanyUsage", w, r)}
}

func (_c *AdminAPI_ResetCompanyUsage_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_ResetCompanyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_ResetCompanyUsage_Call) Return() *AdminAPI_ResetCompanyUsage_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_ResetCompanyUsage_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_ResetCompanyUsage_Call {
	_c.Run(run)
	return _c
}

// ResetPersonalUsage provides a mock function with given fields: w, r
func (_m *AdminAPI) ResetPersonalUsage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_ResetPersonalUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPersonalUsage'
type AdminAPI_ResetPersonalUsage_Call struct {
	*mock.Call
}

// ResetPersonalUsage is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) ResetPersonalUsage(w interface{}, r interface{}) *AdminAPI_ResetPersonalUsage_Call {
	return &AdminAPI_ResetPersonalUsage_Call{Call: _e.mock.On("ResetPersonalUsage", w, r)}
}

func (_c *AdminAPI_ResetPersonalUsage_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_ResetPersonalUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_ResetPersonalUsage_Call) Return() *AdminAPI_ResetPersonalUsage_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_ResetPersonalUsage_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_ResetPersonalUsage_Call {
	_c.Run(run)
	return _c
}

// RevokeAllUserSessions provides a mock function with given fields: w, r
func (_m *AdminAPI) RevokeAllUserSessions(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_RevokeAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserSessions'
type AdminAPI_RevokeAllUserSessions_Call struct {
	*mock.Call
}

// RevokeAllUserSessions is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) RevokeAllUserSessions(w interface{}, r interface{}) *AdminAPI_RevokeAllUserSessions_Call {
	return &AdminAPI_RevokeAllUserSessions_Call{Call: _e.mock.On("RevokeAllUserSessions", w, r)}
}

func (_c *AdminAPI_RevokeAllUserSessions_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_RevokeAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_RevokeAllUserSessions_Call) Return() *AdminAPI_RevokeAllUserSessions_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_RevokeAllUserSessions_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_RevokeAllUserSessions_Call {
	_c.Run(run)
	return _c
}

// RevokeUserSession provides a mock function with given fields: w, r
func (_m *AdminAPI) RevokeUserSession(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_RevokeUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserSession'
type AdminAPI_RevokeUserSession_Call struct {
	*mock.Call
}

// RevokeUserSession is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) RevokeUserSession(w interface{}, r interface{}) *AdminAPI_RevokeUserSession_Call {
	return &AdminAPI_RevokeUserSession_Call{Call: _e.mock.On("RevokeUserSession", w, r)}
}

func (_c *AdminAPI_RevokeUserSession_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_RevokeUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_RevokeUserSession_Call) Return() *AdminAPI_RevokeUserSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_RevokeUserSession_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_RevokeUserSession_Call {
	_c.Run(run)
	return _c
}

// UpdateCompanyTag provides a mock function with given fields: w, r
func (_m *AdminAPI) UpdateCompanyTag(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_UpdateCompanyTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompanyTag'
type AdminAPI_UpdateCompanyTag_Call struct {
	*mock.Call
}

// UpdateCompanyTag is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) UpdateCompanyTag(w interface{}, r interface{}) *AdminAPI_UpdateCompanyTag_Call {
	return &AdminAPI_UpdateCompanyTag_Call{Call: _e.mock.On("UpdateCompanyTag", w, r)}
}

func (_c *AdminAPI_UpdateCompanyTag_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_UpdateCompanyTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_UpdateCompanyTag_Call) Return() *AdminAPI_UpdateCompanyTag_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_UpdateCompanyTag_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_UpdateCompanyTag_Call {
	_c.Run(run)
	return _c
}

// UpdateUserProfile provides a mock function with given fields: w, r
func (_m *AdminAPI) UpdateUserProfile(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type AdminAPI_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) UpdateUserProfile(w interface{}, r interface{}) *AdminAPI_UpdateUserProfile_Call {
	return &AdminAPI_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", w, r)}
}

func (_c *AdminAPI_UpdateUserProfile_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_UpdateUserProfile_Call) Return() *AdminAPI_UpdateUserProfile_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_UpdateUserProfile_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_UpdateUserProfile_Call {
	_c.Run(run)
	return _c
}

// NewAdminAPI creates a new instance of AdminAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminAPI {
	mock := &AdminAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
