// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// developerRepository is an autogenerated mock type for the developerRepository type
type developerRepository struct {
	mock.Mock
}

type developerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *developerRepository) EXPECT() *developerRepository_Expecter {
	return &developerRepository_Expecter{mock: &_m.Mock}
}

// AdjustSandboxWallet provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5
func (_m *developerRepository) AdjustSandboxWallet(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 string, _a4 int64, _a5 string) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5)

	if len(ret) == 0 {
		panic("no return value specified for AdjustSandboxWallet")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, string) (int64, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4, _a5)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, string) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_AdjustSandboxWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustSandboxWallet'
type developerRepository_AdjustSandboxWallet_Call struct {
	*mock.Call
}

// AdjustSandboxWallet is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 string
//   - _a4 int64
//   - _a5 string
func (_e *developerRepository_Expecter) AdjustSandboxWallet(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}, _a5 interface{}) *developerRepository_AdjustSandboxWallet_Call {
	return &developerRepository_AdjustSandboxWallet_Call{Call: _e.mock.On("AdjustSandboxWallet", _a0, _a1, _a2, _a3, _a4, _a5)}
}

func (_c *developerRepository_AdjustSandboxWallet_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 string, _a4 int64, _a5 string)) *developerRepository_AdjustSandboxWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(int64), args[5].(string))
	})
	return _c
}

func (_c *developerRepository_AdjustSandboxWallet_Call) Return(_a0 int64, _a1 error) *developerRepository_AdjustSandboxWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_AdjustSandboxWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, int64, string) (int64, error)) *developerRepository_AdjustSandboxWallet_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateIntegrationKey provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *developerRepository) AuthenticateIntegrationKey(_a0 context.Context, _a1 string, _a2 string, _a3 string) (models.IntegrationPrincipal, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateIntegrationKey")
	}

	var r0 models.IntegrationPrincipal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (models.IntegrationPrincipal, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) models.IntegrationPrincipal); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(models.IntegrationPrincipal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_AuthenticateIntegrationKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateIntegrationKey'
type developerRepository_AuthenticateIntegrationKey_Call struct {
	*mock.Call
}

// AuthenticateIntegrationKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 string
func (_e *developerRepository_Expecter) AuthenticateIntegrationKey(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *developerRepository_AuthenticateIntegrationKey_Call {
	return &developerRepository_AuthenticateIntegrationKey_Call{Call: _e.mock.On("AuthenticateIntegrationKey", _a0, _a1, _a2, _a3)}
}

func (_c *developerRepository_AuthenticateIntegrationKey_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 string)) *developerRepository_AuthenticateIntegrationKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *developerRepository_AuthenticateIntegrationKey_Call) Return(_a0 models.IntegrationPrincipal, _a1 error) *developerRepository_AuthenticateIntegrationKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_AuthenticateIntegrationKey_Call) RunAndReturn(run func(context.Context, string, string, string) (models.IntegrationPrincipal, error)) *developerRepository_AuthenticateIntegrationKey_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeDeveloperApplicationStatus provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *developerRepository) ChangeDeveloperApplicationStatus(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 string) (models.DeveloperApplication, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ChangeDeveloperApplicationStatus")
	}

	var r0 models.DeveloperApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (models.DeveloperApplication, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) models.DeveloperApplication); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(models.DeveloperApplication)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_ChangeDeveloperApplicationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeDeveloperApplicationStatus'
type developerRepository_ChangeDeveloperApplicationStatus_Call struct {
	*mock.Call
}

// ChangeDeveloperApplicationStatus is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 string
func (_e *developerRepository_Expecter) ChangeDeveloperApplicationStatus(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *developerRepository_ChangeDeveloperApplicationStatus_Call {
	return &developerRepository_ChangeDeveloperApplicationStatus_Call{Call: _e.mock.On("ChangeDeveloperApplicationStatus", _a0, _a1, _a2, _a3)}
}

func (_c *developerRepository_ChangeDeveloperApplicationStatus_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 string)) *developerRepository_ChangeDeveloperApplicationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *developerRepository_ChangeDeveloperApplicationStatus_Call) Return(_a0 models.DeveloperApplication, _a1 error) *developerRepository_ChangeDeveloperApplicationStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_ChangeDeveloperApplicationStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (models.DeveloperApplication, error)) *developerRepository_ChangeDeveloperApplicationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDeveloperApplication provides a mock function with given fields: _a0, _a1
func (_m *developerRepository) CreateDeveloperApplication(_a0 context.Context, _a1 models.CreateDeveloperApplicationInput) (models.DeveloperApplication, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeveloperApplication")
	}

	var r0 models.DeveloperApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDeveloperApplicationInput) (models.DeveloperApplication, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDeveloperApplicationInput) models.DeveloperApplication); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.DeveloperApplication)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateDeveloperApplicationInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_CreateDeveloperApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeveloperApplication'
type developerRepository_CreateDeveloperApplication_Call struct {
	*mock.Call
}

// CreateDeveloperApplication is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.CreateDeveloperApplicationInput
func (_e *developerRepository_Expecter) CreateDeveloperApplication(_a0 interface{}, _a1 interface{}) *developerRepository_CreateDeveloperApplication_Call {
	return &developerRepository_CreateDeveloperApplication_Call{Call: _e.mock.On("CreateDeveloperApplication", _a0, _a1)}
}

func (_c *developerRepository_CreateDeveloperApplication_Call) Run(run func(_a0 context.Context, _a1 models.CreateDeveloperApplicationInput)) *developerRepository_CreateDeveloperApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateDeveloperApplicationInput))
	})
	return _c
}

func (_c *developerRepository_CreateDeveloperApplication_Call) Return(_a0 models.DeveloperApplication, _a1 error) *developerRepository_CreateDeveloperApplication_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_CreateDeveloperApplication_Call) RunAndReturn(run func(context.Context, models.CreateDeveloperApplicationInput) (models.DeveloperApplication, error)) *developerRepository_CreateDeveloperApplication_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIntegrationAPIKey provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *developerRepository) CreateIntegrationAPIKey(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 models.CreateIntegrationAPIKeyInput) (models.IntegrationAPIKey, string, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntegrationAPIKey")
	}

	var r0 models.IntegrationAPIKey
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) (models.IntegrationAPIKey, string, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) models.IntegrationAPIKey); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(models.IntegrationAPIKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// developerRepository_CreateIntegrationAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntegrationAPIKey'
type developerRepository_CreateIntegrationAPIKey_Call struct {
	*mock.Call
}

// CreateIntegrationAPIKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 models.CreateIntegrationAPIKeyInput
func (_e *developerRepository_Expecter) CreateIntegrationAPIKey(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *developerRepository_CreateIntegrationAPIKey_Call {
	return &developerRepository_CreateIntegrationAPIKey_Call{Call: _e.mock.On("CreateIntegrationAPIKey", _a0, _a1, _a2, _a3)}
}

func (_c *developerRepository_CreateIntegrationAPIKey_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 models.CreateIntegrationAPIKeyInput)) *developerRepository_CreateIntegrationAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(models.CreateIntegrationAPIKeyInput))
	})
	return _c
}

func (_c *developerRepository_CreateIntegrationAPIKey_Call) Return(_a0 models.IntegrationAPIKey, _a1 string, _a2 error) *developerRepository_CreateIntegrationAPIKey_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *developerRepository_CreateIntegrationAPIKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) (models.IntegrationAPIKey, string, error)) *developerRepository_CreateIntegrationAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIntegrationAPIKeyForServiceAccount provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *developerRepository) CreateIntegrationAPIKeyForServiceAccount(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 models.CreateIntegrationAPIKeyInput) (models.IntegrationAPIKey, string, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntegrationAPIKeyForServiceAccount")
	}

	var r0 models.IntegrationAPIKey
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) (models.IntegrationAPIKey, string, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) models.IntegrationAPIKey); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(models.IntegrationAPIKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntegrationAPIKeyForServiceAccount'
type developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call struct {
	*mock.Call
}

// CreateIntegrationAPIKeyForServiceAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 models.CreateIntegrationAPIKeyInput
func (_e *developerRepository_Expecter) CreateIntegrationAPIKeyForServiceAccount(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call {
	return &developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call{Call: _e.mock.On("CreateIntegrationAPIKeyForServiceAccount", _a0, _a1, _a2, _a3)}
}

func (_c *developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 models.CreateIntegrationAPIKeyInput)) *developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(models.CreateIntegrationAPIKeyInput))
	})
	return _c
}

func (_c *developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call) Return(_a0 models.IntegrationAPIKey, _a1 string, _a2 error) *developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, models.CreateIntegrationAPIKeyInput) (models.IntegrationAPIKey, string, error)) *developerRepository_CreateIntegrationAPIKeyForServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIntegrationServiceAccount provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *developerRepository) CreateIntegrationServiceAccount(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 string, _a4 []string) (models.IntegrationServiceAccount, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntegrationServiceAccount")
	}

	var r0 models.IntegrationServiceAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, []string) (models.IntegrationServiceAccount, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, []string) models.IntegrationServiceAccount); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Get(0).(models.IntegrationServiceAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, []string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_CreateIntegrationServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntegrationServiceAccount'
type developerRepository_CreateIntegrationServiceAccount_Call struct {
	*mock.Call
}

// CreateIntegrationServiceAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 string
//   - _a4 []string
func (_e *developerRepository_Expecter) CreateIntegrationServiceAccount(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *developerRepository_CreateIntegrationServiceAccount_Call {
	return &developerRepository_CreateIntegrationServiceAccount_Call{Call: _e.mock.On("CreateIntegrationServiceAccount", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *developerRepository_CreateIntegrationServiceAccount_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 string, _a4 []string)) *developerRepository_CreateIntegrationServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *developerRepository_CreateIntegrationServiceAccount_Call) Return(_a0 models.IntegrationServiceAccount, _a1 error) *developerRepository_CreateIntegrationServiceAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_CreateIntegrationServiceAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, []string) (models.IntegrationServiceAccount, error)) *developerRepository_CreateIntegrationServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeveloperApplication provides a mock function with given fields: _a0, _a1, _a2
func (_m *developerRepository) GetDeveloperApplication(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (models.DeveloperApplication, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetDeveloperApplication")
	}

	var r0 models.DeveloperApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.DeveloperApplication, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.DeveloperApplication); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(models.DeveloperApplication)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_GetDeveloperApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeveloperApplication'
type developerRepository_GetDeveloperApplication_Call struct {
	*mock.Call
}

// GetDeveloperApplication is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *developerRepository_Expecter) GetDeveloperApplication(_a0 interface{}, _a1 interface{}, _a2 interface{}) *developerRepository_GetDeveloperApplication_Call {
	return &developerRepository_GetDeveloperApplication_Call{Call: _e.mock.On("GetDeveloperApplication", _a0, _a1, _a2)}
}

func (_c *developerRepository_GetDeveloperApplication_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *developerRepository_GetDeveloperApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *developerRepository_GetDeveloperApplication_Call) Return(_a0 models.DeveloperApplication, _a1 error) *developerRepository_GetDeveloperApplication_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_GetDeveloperApplication_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.DeveloperApplication, error)) *developerRepository_GetDeveloperApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetSandboxWallet provides a mock function with given fields: _a0, _a1, _a2
func (_m *developerRepository) GetSandboxWallet(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (models.SandboxWalletDashboard, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetSandboxWallet")
	}

	var r0 models.SandboxWalletDashboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.SandboxWalletDashboard, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.SandboxWalletDashboard); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(models.SandboxWalletDashboard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_GetSandboxWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSandboxWallet'
type developerRepository_GetSandboxWallet_Call struct {
	*mock.Call
}

// GetSandboxWallet is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *developerRepository_Expecter) GetSandboxWallet(_a0 interface{}, _a1 interface{}, _a2 interface{}) *developerRepository_GetSandboxWallet_Call {
	return &developerRepository_GetSandboxWallet_Call{Call: _e.mock.On("GetSandboxWallet", _a0, _a1, _a2)}
}

func (_c *developerRepository_GetSandboxWallet_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *developerRepository_GetSandboxWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *developerRepository_GetSandboxWallet_Call) Return(_a0 models.SandboxWalletDashboard, _a1 error) *developerRepository_GetSandboxWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_GetSandboxWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.SandboxWalletDashboard, error)) *developerRepository_GetSandboxWallet_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeveloperApplications provides a mock function with given fields: _a0, _a1, _a2
func (_m *developerRepository) ListDeveloperApplications(_a0 context.Context, _a1 string, _a2 uuid.UUID) ([]models.DeveloperApplication, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ListDeveloperApplications")
	}

	var r0 []models.DeveloperApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]models.DeveloperApplication, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []models.DeveloperApplication); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DeveloperApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_ListDeveloperApplications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeveloperApplications'
type developerRepository_ListDeveloperApplications_Call struct {
	*mock.Call
}

// ListDeveloperApplications is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 uuid.UUID
func (_e *developerRepository_Expecter) ListDeveloperApplications(_a0 interface{}, _a1 interface{}, _a2 interface{}) *developerRepository_ListDeveloperApplications_Call {
	return &developerRepository_ListDeveloperApplications_Call{Call: _e.mock.On("ListDeveloperApplications", _a0, _a1, _a2)}
}

func (_c *developerRepository_ListDeveloperApplications_Call) Run(run func(_a0 context.Context, _a1 string, _a2 uuid.UUID)) *developerRepository_ListDeveloperApplications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *developerRepository_ListDeveloperApplications_Call) Return(_a0 []models.DeveloperApplication, _a1 error) *developerRepository_ListDeveloperApplications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_ListDeveloperApplications_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) ([]models.DeveloperApplication, error)) *developerRepository_ListDeveloperApplications_Call {
	_c.Call.Return(run)
	return _c
}

// ListIntegrationAPIKeys provides a mock function with given fields: _a0, _a1, _a2
func (_m *developerRepository) ListIntegrationAPIKeys(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) ([]models.IntegrationAPIKey, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ListIntegrationAPIKeys")
	}

	var r0 []models.IntegrationAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.IntegrationAPIKey, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.IntegrationAPIKey); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IntegrationAPIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_ListIntegrationAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIntegrationAPIKeys'
type developerRepository_ListIntegrationAPIKeys_Call struct {
	*mock.Call
}

// ListIntegrationAPIKeys is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *developerRepository_Expecter) ListIntegrationAPIKeys(_a0 interface{}, _a1 interface{}, _a2 interface{}) *developerRepository_ListIntegrationAPIKeys_Call {
	return &developerRepository_ListIntegrationAPIKeys_Call{Call: _e.mock.On("ListIntegrationAPIKeys", _a0, _a1, _a2)}
}

func (_c *developerRepository_ListIntegrationAPIKeys_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *developerRepository_ListIntegrationAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *developerRepository_ListIntegrationAPIKeys_Call) Return(_a0 []models.IntegrationAPIKey, _a1 error) *developerRepository_ListIntegrationAPIKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_ListIntegrationAPIKeys_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.IntegrationAPIKey, error)) *developerRepository_ListIntegrationAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListIntegrationServiceAccounts provides a mock function with given fields: _a0, _a1, _a2
func (_m *developerRepository) ListIntegrationServiceAccounts(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) ([]models.IntegrationServiceAccount, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ListIntegrationServiceAccounts")
	}

	var r0 []models.IntegrationServiceAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.IntegrationServiceAccount, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.IntegrationServiceAccount); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IntegrationServiceAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_ListIntegrationServiceAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIntegrationServiceAccounts'
type developerRepository_ListIntegrationServiceAccounts_Call struct {
	*mock.Call
}

// ListIntegrationServiceAccounts is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *developerRepository_Expecter) ListIntegrationServiceAccounts(_a0 interface{}, _a1 interface{}, _a2 interface{}) *developerRepository_ListIntegrationServiceAccounts_Call {
	return &developerRepository_ListIntegrationServiceAccounts_Call{Call: _e.mock.On("ListIntegrationServiceAccounts", _a0, _a1, _a2)}
}

func (_c *developerRepository_ListIntegrationServiceAccounts_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *developerRepository_ListIntegrationServiceAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *developerRepository_ListIntegrationServiceAccounts_Call) Return(_a0 []models.IntegrationServiceAccount, _a1 error) *developerRepository_ListIntegrationServiceAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_ListIntegrationServiceAccounts_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.IntegrationServiceAccount, error)) *developerRepository_ListIntegrationServiceAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeIntegrationAPIKey provides a mock function with given fields: _a0, _a1, _a2
func (_m *developerRepository) RevokeIntegrationAPIKey(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RevokeIntegrationAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// developerRepository_RevokeIntegrationAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeIntegrationAPIKey'
type developerRepository_RevokeIntegrationAPIKey_Call struct {
	*mock.Call
}

// RevokeIntegrationAPIKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *developerRepository_Expecter) RevokeIntegrationAPIKey(_a0 interface{}, _a1 interface{}, _a2 interface{}) *developerRepository_RevokeIntegrationAPIKey_Call {
	return &developerRepository_RevokeIntegrationAPIKey_Call{Call: _e.mock.On("RevokeIntegrationAPIKey", _a0, _a1, _a2)}
}

func (_c *developerRepository_RevokeIntegrationAPIKey_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *developerRepository_RevokeIntegrationAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *developerRepository_RevokeIntegrationAPIKey_Call) Return(_a0 error) *developerRepository_RevokeIntegrationAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *developerRepository_RevokeIntegrationAPIKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *developerRepository_RevokeIntegrationAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeIntegrationServiceAccount provides a mock function with given fields: _a0, _a1, _a2
func (_m *developerRepository) RevokeIntegrationServiceAccount(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RevokeIntegrationServiceAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// developerRepository_RevokeIntegrationServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeIntegrationServiceAccount'
type developerRepository_RevokeIntegrationServiceAccount_Call struct {
	*mock.Call
}

// RevokeIntegrationServiceAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *developerRepository_Expecter) RevokeIntegrationServiceAccount(_a0 interface{}, _a1 interface{}, _a2 interface{}) *developerRepository_RevokeIntegrationServiceAccount_Call {
	return &developerRepository_RevokeIntegrationServiceAccount_Call{Call: _e.mock.On("RevokeIntegrationServiceAccount", _a0, _a1, _a2)}
}

func (_c *developerRepository_RevokeIntegrationServiceAccount_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *developerRepository_RevokeIntegrationServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *developerRepository_RevokeIntegrationServiceAccount_Call) Return(_a0 error) *developerRepository_RevokeIntegrationServiceAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *developerRepository_RevokeIntegrationServiceAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *developerRepository_RevokeIntegrationServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RotateIntegrationAPIKey provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *developerRepository) RotateIntegrationAPIKey(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 time.Duration) (models.IntegrationAPIKey, string, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for RotateIntegrationAPIKey")
	}

	var r0 models.IntegrationAPIKey
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Duration) (models.IntegrationAPIKey, string, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Duration) models.IntegrationAPIKey); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(models.IntegrationAPIKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Duration) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, time.Duration) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// developerRepository_RotateIntegrationAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateIntegrationAPIKey'
type developerRepository_RotateIntegrationAPIKey_Call struct {
	*mock.Call
}

// RotateIntegrationAPIKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 time.Duration
func (_e *developerRepository_Expecter) RotateIntegrationAPIKey(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *developerRepository_RotateIntegrationAPIKey_Call {
	return &developerRepository_RotateIntegrationAPIKey_Call{Call: _e.mock.On("RotateIntegrationAPIKey", _a0, _a1, _a2, _a3)}
}

func (_c *developerRepository_RotateIntegrationAPIKey_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 time.Duration)) *developerRepository_RotateIntegrationAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(time.Duration))
	})
	return _c
}

func (_c *developerRepository_RotateIntegrationAPIKey_Call) Return(_a0 models.IntegrationAPIKey, _a1 string, _a2 error) *developerRepository_RotateIntegrationAPIKey_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *developerRepository_RotateIntegrationAPIKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, time.Duration) (models.IntegrationAPIKey, string, error)) *developerRepository_RotateIntegrationAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeveloperApplication provides a mock function with given fields: _a0, _a1
func (_m *developerRepository) UpdateDeveloperApplication(_a0 context.Context, _a1 models.UpdateDeveloperApplicationInput) (models.DeveloperApplication, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeveloperApplication")
	}

	var r0 models.DeveloperApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateDeveloperApplicationInput) (models.DeveloperApplication, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateDeveloperApplicationInput) models.DeveloperApplication); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.DeveloperApplication)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateDeveloperApplicationInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// developerRepository_UpdateDeveloperApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeveloperApplication'
type developerRepository_UpdateDeveloperApplication_Call struct {
	*mock.Call
}

// UpdateDeveloperApplication is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.UpdateDeveloperApplicationInput
func (_e *developerRepository_Expecter) UpdateDeveloperApplication(_a0 interface{}, _a1 interface{}) *developerRepository_UpdateDeveloperApplication_Call {
	return &developerRepository_UpdateDeveloperApplication_Call{Call: _e.mock.On("UpdateDeveloperApplication", _a0, _a1)}
}

func (_c *developerRepository_UpdateDeveloperApplication_Call) Run(run func(_a0 context.Context, _a1 models.UpdateDeveloperApplicationInput)) *developerRepository_UpdateDeveloperApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateDeveloperApplicationInput))
	})
	return _c
}

func (_c *developerRepository_UpdateDeveloperApplication_Call) Return(_a0 models.DeveloperApplication, _a1 error) *developerRepository_UpdateDeveloperApplication_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *developerRepository_UpdateDeveloperApplication_Call) RunAndReturn(run func(context.Context, models.UpdateDeveloperApplicationInput) (models.DeveloperApplication, error)) *developerRepository_UpdateDeveloperApplication_Call {
	_c.Call.Return(run)
	return _c
}

// newDeveloperRepository creates a new instance of developerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDeveloperRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *developerRepository {
	mock := &developerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
