// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// creditDashboardRepository is an autogenerated mock type for the creditDashboardRepository type
type creditDashboardRepository struct {
	mock.Mock
}

type creditDashboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *creditDashboardRepository) EXPECT() *creditDashboardRepository_Expecter {
	return &creditDashboardRepository_Expecter{mock: &_m.Mock}
}

// GetCreditDashboard provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *creditDashboardRepository) GetCreditDashboard(_a0 context.Context, _a1 models.Subscription, _a2 time.Time, _a3 time.Time) (models.CreditDashboard, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for GetCreditDashboard")
	}

	var r0 models.CreditDashboard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Subscription, time.Time, time.Time) (models.CreditDashboard, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Subscription, time.Time, time.Time) models.CreditDashboard); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(models.CreditDashboard)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Subscription, time.Time, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditDashboardRepository_GetCreditDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreditDashboard'
type creditDashboardRepository_GetCreditDashboard_Call struct {
	*mock.Call
}

// GetCreditDashboard is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Subscription
//   - _a2 time.Time
//   - _a3 time.Time
func (_e *creditDashboardRepository_Expecter) GetCreditDashboard(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *creditDashboardRepository_GetCreditDashboard_Call {
	return &creditDashboardRepository_GetCreditDashboard_Call{Call: _e.mock.On("GetCreditDashboard", _a0, _a1, _a2, _a3)}
}

func (_c *creditDashboardRepository_GetCreditDashboard_Call) Run(run func(_a0 context.Context, _a1 models.Subscription, _a2 time.Time, _a3 time.Time)) *creditDashboardRepository_GetCreditDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Subscription), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *creditDashboardRepository_GetCreditDashboard_Call) Return(_a0 models.CreditDashboard, _a1 error) *creditDashboardRepository_GetCreditDashboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditDashboardRepository_GetCreditDashboard_Call) RunAndReturn(run func(context.Context, models.Subscription, time.Time, time.Time) (models.CreditDashboard, error)) *creditDashboardRepository_GetCreditDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// newCreditDashboardRepository creates a new instance of creditDashboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCreditDashboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *creditDashboardRepository {
	mock := &creditDashboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
