// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "verbatrace/monolit/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// creditOperationRepository is an autogenerated mock type for the creditOperationRepository type
type creditOperationRepository struct {
	mock.Mock
}

type creditOperationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *creditOperationRepository) EXPECT() *creditOperationRepository_Expecter {
	return &creditOperationRepository_Expecter{mock: &_m.Mock}
}

// CreditsForOperationProviderCost provides a mock function with given fields: _a0, _a1, _a2
func (_m *creditOperationRepository) CreditsForOperationProviderCost(_a0 context.Context, _a1 uuid.UUID, _a2 int64) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreditsForOperationProviderCost")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (int64, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_CreditsForOperationProviderCost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreditsForOperationProviderCost'
type creditOperationRepository_CreditsForOperationProviderCost_Call struct {
	*mock.Call
}

// CreditsForOperationProviderCost is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 int64
func (_e *creditOperationRepository_Expecter) CreditsForOperationProviderCost(_a0 interface{}, _a1 interface{}, _a2 interface{}) *creditOperationRepository_CreditsForOperationProviderCost_Call {
	return &creditOperationRepository_CreditsForOperationProviderCost_Call{Call: _e.mock.On("CreditsForOperationProviderCost", _a0, _a1, _a2)}
}

func (_c *creditOperationRepository_CreditsForOperationProviderCost_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 int64)) *creditOperationRepository_CreditsForOperationProviderCost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *creditOperationRepository_CreditsForOperationProviderCost_Call) Return(_a0 int64, _a1 error) *creditOperationRepository_CreditsForOperationProviderCost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_CreditsForOperationProviderCost_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (int64, error)) *creditOperationRepository_CreditsForOperationProviderCost_Call {
	_c.Call.Return(run)
	return _c
}

// IntegrationBillingContextForCall provides a mock function with given fields: _a0, _a1
func (_m *creditOperationRepository) IntegrationBillingContextForCall(_a0 context.Context, _a1 uuid.UUID) (uuid.NullUUID, string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IntegrationBillingContextForCall")
	}

	var r0 uuid.NullUUID
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.NullUUID, string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.NullUUID); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uuid.NullUUID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// creditOperationRepository_IntegrationBillingContextForCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntegrationBillingContextForCall'
type creditOperationRepository_IntegrationBillingContextForCall_Call struct {
	*mock.Call
}

// IntegrationBillingContextForCall is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *creditOperationRepository_Expecter) IntegrationBillingContextForCall(_a0 interface{}, _a1 interface{}) *creditOperationRepository_IntegrationBillingContextForCall_Call {
	return &creditOperationRepository_IntegrationBillingContextForCall_Call{Call: _e.mock.On("IntegrationBillingContextForCall", _a0, _a1)}
}

func (_c *creditOperationRepository_IntegrationBillingContextForCall_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *creditOperationRepository_IntegrationBillingContextForCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *creditOperationRepository_IntegrationBillingContextForCall_Call) Return(_a0 uuid.NullUUID, _a1 string, _a2 error) *creditOperationRepository_IntegrationBillingContextForCall_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *creditOperationRepository_IntegrationBillingContextForCall_Call) RunAndReturn(run func(context.Context, uuid.UUID) (uuid.NullUUID, string, error)) *creditOperationRepository_IntegrationBillingContextForCall_Call {
	_c.Call.Return(run)
	return _c
}

// IsSandboxMockCall provides a mock function with given fields: _a0, _a1
func (_m *creditOperationRepository) IsSandboxMockCall(_a0 context.Context, _a1 uuid.UUID) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IsSandboxMockCall")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_IsSandboxMockCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSandboxMockCall'
type creditOperationRepository_IsSandboxMockCall_Call struct {
	*mock.Call
}

// IsSandboxMockCall is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *creditOperationRepository_Expecter) IsSandboxMockCall(_a0 interface{}, _a1 interface{}) *creditOperationRepository_IsSandboxMockCall_Call {
	return &creditOperationRepository_IsSandboxMockCall_Call{Call: _e.mock.On("IsSandboxMockCall", _a0, _a1)}
}

func (_c *creditOperationRepository_IsSandboxMockCall_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *creditOperationRepository_IsSandboxMockCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *creditOperationRepository_IsSandboxMockCall_Call) Return(_a0 bool, _a1 error) *creditOperationRepository_IsSandboxMockCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_IsSandboxMockCall_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *creditOperationRepository_IsSandboxMockCall_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCreditOperationProviderRunning provides a mock function with given fields: _a0, _a1
func (_m *creditOperationRepository) MarkCreditOperationProviderRunning(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MarkCreditOperationProviderRunning")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// creditOperationRepository_MarkCreditOperationProviderRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCreditOperationProviderRunning'
type creditOperationRepository_MarkCreditOperationProviderRunning_Call struct {
	*mock.Call
}

// MarkCreditOperationProviderRunning is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *creditOperationRepository_Expecter) MarkCreditOperationProviderRunning(_a0 interface{}, _a1 interface{}) *creditOperationRepository_MarkCreditOperationProviderRunning_Call {
	return &creditOperationRepository_MarkCreditOperationProviderRunning_Call{Call: _e.mock.On("MarkCreditOperationProviderRunning", _a0, _a1)}
}

func (_c *creditOperationRepository_MarkCreditOperationProviderRunning_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *creditOperationRepository_MarkCreditOperationProviderRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *creditOperationRepository_MarkCreditOperationProviderRunning_Call) Return(_a0 error) *creditOperationRepository_MarkCreditOperationProviderRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *creditOperationRepository_MarkCreditOperationProviderRunning_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *creditOperationRepository_MarkCreditOperationProviderRunning_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCreditOperationReconciling provides a mock function with given fields: _a0, _a1, _a2
func (_m *creditOperationRepository) MarkCreditOperationReconciling(_a0 context.Context, _a1 uuid.UUID, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MarkCreditOperationReconciling")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// creditOperationRepository_MarkCreditOperationReconciling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCreditOperationReconciling'
type creditOperationRepository_MarkCreditOperationReconciling_Call struct {
	*mock.Call
}

// MarkCreditOperationReconciling is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 string
func (_e *creditOperationRepository_Expecter) MarkCreditOperationReconciling(_a0 interface{}, _a1 interface{}, _a2 interface{}) *creditOperationRepository_MarkCreditOperationReconciling_Call {
	return &creditOperationRepository_MarkCreditOperationReconciling_Call{Call: _e.mock.On("MarkCreditOperationReconciling", _a0, _a1, _a2)}
}

func (_c *creditOperationRepository_MarkCreditOperationReconciling_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 string)) *creditOperationRepository_MarkCreditOperationReconciling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *creditOperationRepository_MarkCreditOperationReconciling_Call) Return(_a0 error) *creditOperationRepository_MarkCreditOperationReconciling_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *creditOperationRepository_MarkCreditOperationReconciling_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *creditOperationRepository_MarkCreditOperationReconciling_Call {
	_c.Call.Return(run)
	return _c
}

// MaximumAnalysisCredits provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *creditOperationRepository) MaximumAnalysisCredits(_a0 context.Context, _a1 int64, _a2 int64, _a3 time.Time) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for MaximumAnalysisCredits")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) (int64, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_MaximumAnalysisCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaximumAnalysisCredits'
type creditOperationRepository_MaximumAnalysisCredits_Call struct {
	*mock.Call
}

// MaximumAnalysisCredits is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
//   - _a2 int64
//   - _a3 time.Time
func (_e *creditOperationRepository_Expecter) MaximumAnalysisCredits(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *creditOperationRepository_MaximumAnalysisCredits_Call {
	return &creditOperationRepository_MaximumAnalysisCredits_Call{Call: _e.mock.On("MaximumAnalysisCredits", _a0, _a1, _a2, _a3)}
}

func (_c *creditOperationRepository_MaximumAnalysisCredits_Call) Run(run func(_a0 context.Context, _a1 int64, _a2 int64, _a3 time.Time)) *creditOperationRepository_MaximumAnalysisCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(time.Time))
	})
	return _c
}

func (_c *creditOperationRepository_MaximumAnalysisCredits_Call) Return(_a0 int64, _a1 error) *creditOperationRepository_MaximumAnalysisCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_MaximumAnalysisCredits_Call) RunAndReturn(run func(context.Context, int64, int64, time.Time) (int64, error)) *creditOperationRepository_MaximumAnalysisCredits_Call {
	_c.Call.Return(run)
	return _c
}

// MaximumGenerationCredits provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5
func (_m *creditOperationRepository) MaximumGenerationCredits(_a0 context.Context, _a1 int64, _a2 int64, _a3 string, _a4 string, _a5 time.Time) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5)

	if len(ret) == 0 {
		panic("no return value specified for MaximumGenerationCredits")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, time.Time) (int64, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4, _a5)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, time.Time) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_MaximumGenerationCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaximumGenerationCredits'
type creditOperationRepository_MaximumGenerationCredits_Call struct {
	*mock.Call
}

// MaximumGenerationCredits is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
//   - _a2 int64
//   - _a3 string
//   - _a4 string
//   - _a5 time.Time
func (_e *creditOperationRepository_Expecter) MaximumGenerationCredits(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}, _a5 interface{}) *creditOperationRepository_MaximumGenerationCredits_Call {
	return &creditOperationRepository_MaximumGenerationCredits_Call{Call: _e.mock.On("MaximumGenerationCredits", _a0, _a1, _a2, _a3, _a4, _a5)}
}

func (_c *creditOperationRepository_MaximumGenerationCredits_Call) Run(run func(_a0 context.Context, _a1 int64, _a2 int64, _a3 string, _a4 string, _a5 time.Time)) *creditOperationRepository_MaximumGenerationCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string), args[4].(string), args[5].(time.Time))
	})
	return _c
}

func (_c *creditOperationRepository_MaximumGenerationCredits_Call) Return(_a0 int64, _a1 error) *creditOperationRepository_MaximumGenerationCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_MaximumGenerationCredits_Call) RunAndReturn(run func(context.Context, int64, int64, string, string, time.Time) (int64, error)) *creditOperationRepository_MaximumGenerationCredits_Call {
	_c.Call.Return(run)
	return _c
}

// MaximumTranscriptionCredits provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *creditOperationRepository) MaximumTranscriptionCredits(_a0 context.Context, _a1 int64, _a2 string, _a3 time.Time) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for MaximumTranscriptionCredits")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, time.Time) (int64, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, time.Time) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_MaximumTranscriptionCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaximumTranscriptionCredits'
type creditOperationRepository_MaximumTranscriptionCredits_Call struct {
	*mock.Call
}

// MaximumTranscriptionCredits is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
//   - _a2 string
//   - _a3 time.Time
func (_e *creditOperationRepository_Expecter) MaximumTranscriptionCredits(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *creditOperationRepository_MaximumTranscriptionCredits_Call {
	return &creditOperationRepository_MaximumTranscriptionCredits_Call{Call: _e.mock.On("MaximumTranscriptionCredits", _a0, _a1, _a2, _a3)}
}

func (_c *creditOperationRepository_MaximumTranscriptionCredits_Call) Run(run func(_a0 context.Context, _a1 int64, _a2 string, _a3 time.Time)) *creditOperationRepository_MaximumTranscriptionCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *creditOperationRepository_MaximumTranscriptionCredits_Call) Return(_a0 int64, _a1 error) *creditOperationRepository_MaximumTranscriptionCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_MaximumTranscriptionCredits_Call) RunAndReturn(run func(context.Context, int64, string, time.Time) (int64, error)) *creditOperationRepository_MaximumTranscriptionCredits_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveCredits provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *creditOperationRepository) ReserveCredits(_a0 context.Context, _a1 models.Subscription, _a2 models.ReserveCreditsInput, _a3 time.Time) (models.CreditOperation, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ReserveCredits")
	}

	var r0 models.CreditOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Subscription, models.ReserveCreditsInput, time.Time) (models.CreditOperation, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Subscription, models.ReserveCreditsInput, time.Time) models.CreditOperation); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(models.CreditOperation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Subscription, models.ReserveCreditsInput, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_ReserveCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveCredits'
type creditOperationRepository_ReserveCredits_Call struct {
	*mock.Call
}

// ReserveCredits is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Subscription
//   - _a2 models.ReserveCreditsInput
//   - _a3 time.Time
func (_e *creditOperationRepository_Expecter) ReserveCredits(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *creditOperationRepository_ReserveCredits_Call {
	return &creditOperationRepository_ReserveCredits_Call{Call: _e.mock.On("ReserveCredits", _a0, _a1, _a2, _a3)}
}

func (_c *creditOperationRepository_ReserveCredits_Call) Run(run func(_a0 context.Context, _a1 models.Subscription, _a2 models.ReserveCreditsInput, _a3 time.Time)) *creditOperationRepository_ReserveCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Subscription), args[2].(models.ReserveCreditsInput), args[3].(time.Time))
	})
	return _c
}

func (_c *creditOperationRepository_ReserveCredits_Call) Return(_a0 models.CreditOperation, _a1 error) *creditOperationRepository_ReserveCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_ReserveCredits_Call) RunAndReturn(run func(context.Context, models.Subscription, models.ReserveCreditsInput, time.Time) (models.CreditOperation, error)) *creditOperationRepository_ReserveCredits_Call {
	_c.Call.Return(run)
	return _c
}

// SettleCredits provides a mock function with given fields: _a0, _a1, _a2
func (_m *creditOperationRepository) SettleCredits(_a0 context.Context, _a1 models.SettleCreditsInput, _a2 time.Time) (models.CreditOperation, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SettleCredits")
	}

	var r0 models.CreditOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SettleCreditsInput, time.Time) (models.CreditOperation, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.SettleCreditsInput, time.Time) models.CreditOperation); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(models.CreditOperation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.SettleCreditsInput, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_SettleCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SettleCredits'
type creditOperationRepository_SettleCredits_Call struct {
	*mock.Call
}

// SettleCredits is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.SettleCreditsInput
//   - _a2 time.Time
func (_e *creditOperationRepository_Expecter) SettleCredits(_a0 interface{}, _a1 interface{}, _a2 interface{}) *creditOperationRepository_SettleCredits_Call {
	return &creditOperationRepository_SettleCredits_Call{Call: _e.mock.On("SettleCredits", _a0, _a1, _a2)}
}

func (_c *creditOperationRepository_SettleCredits_Call) Run(run func(_a0 context.Context, _a1 models.SettleCreditsInput, _a2 time.Time)) *creditOperationRepository_SettleCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.SettleCreditsInput), args[2].(time.Time))
	})
	return _c
}

func (_c *creditOperationRepository_SettleCredits_Call) Return(_a0 models.CreditOperation, _a1 error) *creditOperationRepository_SettleCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_SettleCredits_Call) RunAndReturn(run func(context.Context, models.SettleCreditsInput, time.Time) (models.CreditOperation, error)) *creditOperationRepository_SettleCredits_Call {
	_c.Call.Return(run)
	return _c
}

// TranscriptionProviderCostNanoUSD provides a mock function with given fields: _a0, _a1, _a2
func (_m *creditOperationRepository) TranscriptionProviderCostNanoUSD(_a0 context.Context, _a1 uuid.UUID, _a2 int64) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for TranscriptionProviderCostNanoUSD")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (int64, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// creditOperationRepository_TranscriptionProviderCostNanoUSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranscriptionProviderCostNanoUSD'
type creditOperationRepository_TranscriptionProviderCostNanoUSD_Call struct {
	*mock.Call
}

// TranscriptionProviderCostNanoUSD is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 int64
func (_e *creditOperationRepository_Expecter) TranscriptionProviderCostNanoUSD(_a0 interface{}, _a1 interface{}, _a2 interface{}) *creditOperationRepository_TranscriptionProviderCostNanoUSD_Call {
	return &creditOperationRepository_TranscriptionProviderCostNanoUSD_Call{Call: _e.mock.On("TranscriptionProviderCostNanoUSD", _a0, _a1, _a2)}
}

func (_c *creditOperationRepository_TranscriptionProviderCostNanoUSD_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 int64)) *creditOperationRepository_TranscriptionProviderCostNanoUSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *creditOperationRepository_TranscriptionProviderCostNanoUSD_Call) Return(_a0 int64, _a1 error) *creditOperationRepository_TranscriptionProviderCostNanoUSD_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *creditOperationRepository_TranscriptionProviderCostNanoUSD_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (int64, error)) *creditOperationRepository_TranscriptionProviderCostNanoUSD_Call {
	_c.Call.Return(run)
	return _c
}

// newCreditOperationRepository creates a new instance of creditOperationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCreditOperationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *creditOperationRepository {
	mock := &creditOperationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
